What is `One-Hot encoding`?

Supose we have a column **Color** and it has values like Red, Yellow and Green. What we do in one-hot encoding is, we create 3 new columns named Red. Yellow and Green and then to show Red we insert 1 and 0 to others.
For eg. Red = [1, 0, 0]<br>
Yellow = [0, 1, 0]<br>
Green = [0, 0, 1]

Now what if we have 50 unique values in a column? Yes, we will create 50 columns for that.<br>
But then the dimension of our dataset will increase. Yes but there's no other way. But if some values are repeating frequently, we can create columns of those frequent values and all the other(non frequent values) values can be put under one single column named `Other`.<br>

Moreover, we delete one column from all the columns to avoid Multicolinearity.`Multicolinearity` means all the columns are dependent on each other.
It ceates problem when we deal with Linear models like Linear regression or Logistic regression. We'll learn what is multicoliniarty and how it affects Linear models n detail when we'll study Linear models. But as for now, just remember, we remove one column to avoid the problem of Multicolinearity.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df =  pd.read_csv("00 cars.csv")
df.sample(5)

# Here 'brand' is a Nominal column so we'll apply one-hot encoding to it. It has 32 unique values.

        brand  km_driven    fuel         owner  selling_price
4870     Tata      70000  Diesel  Second Owner         189000
7589   Maruti       1000  Petrol   First Owner         445000
4054     Tata     140000  Diesel   First Owner         229999
1561     Audi      31800  Diesel   First Owner        3975000
3265  Hyundai      48000  Diesel   First Owner         670000

In [3]:
df['brand'].value_counts().count()

32

In [4]:
df.brand.nunique()

32

# 1) One-Hot encoding using Pandas.

In [5]:
# Firstly we are working with 'Fuel' and 'owner' columns. We'll deal with 'brand' column in the end.

pd.get_dummies(df, columns = ['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

In [6]:
# Here we're getting 12 columns and we've not delt with the problem of Multicolinearity. Let's deal with it.

# 2) n - 1 encoding.

In [8]:
df2 = pd.read_csv("00 cars.csv")
df2.sample(5)

           brand  km_driven    fuel         owner  selling_price
5033      Nissan      40000  Diesel   First Owner         475000
7817        Tata      88000  Diesel   First Owner         110000
1142       Honda      56494  Petrol   First Owner         550000
6126  Volkswagen      40000  Petrol  Second Owner         395000
3213    Mahindra     110000  Diesel  Second Owner         430000

In [9]:
pd.get_dummies(df2, columns = ['fuel', 'owner'], drop_first = True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

In [10]:
# We can see we're getting only 10 columns. It is bcz column for one category got removed from both the columns.

# Note: This One-Hot encoding through `pandas` is just for showing how it works. In real world, when we work with model building, we don't use pandas for it bcz it doesn't remember the order of the columns. We use `OneHotEncoder` class of `sklearn` library and `preprocessing` module.

# 3) One-Hot encoding using sklearn.

In [ ]:
df2 = pd.read_csv("00 cars.csv")
df2.sample(5)

In [13]:
x = df.iloc[:, 0:4]
y = df.drop(x, axis = 'columns')
print(x.head())

print()
print()
print()

print(y)

     brand  km_driven    fuel         owner
0   Maruti     145500  Diesel   First Owner
1    Skoda     120000  Diesel  Second Owner
2    Honda     140000  Petrol   Third Owner
3  Hyundai     127000  Diesel   First Owner
4   Maruti     120000  Petrol   First Owner



      selling_price
0            450000
1            370000
2            158000
3            225000
4            130000
...             ...
8123         320000
8124         135000
8125         382000
8126         290000
8127         290000

[8128 rows x 1 columns]

In [14]:
# Spliting the data into train and test

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [15]:
# Applying One-Hot encoding

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop = 'first', sparse = False)
# Here we are droping the first column to avoid the problem of multicolinearity and sparse = False means we don't want sparse matrix in return

# Here, we will apply OHE to 'fuel' and 'owner' columns. So the process will be, first we'll apply it to these columns and then
# add the result with the original DataFrame.

# Fitting and transforming x_train and columns are 'fuel' and 'owner'
ohe.fit_transform(x_train[['fuel', 'owner']])

C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [16]:
x_train_new = ohe.fit_transform(x_train[['fuel', 'owner']])
x_train_new

C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [17]:
# Transforming x_test and columns are 'fuel' and 'owner'


x_test_new = ohe.transform(x_test[['fuel', 'owner']])
x_test_new

array([[1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [18]:
# Now we should have 9 columns 4 from fuel and 5 from owner. But as we are droping the first column from both 
# 'fuel' and 'owner', we'll have 7 columns.

print(x_train_new.shape)
print(x_test_new.shape)

(6502, 7)
(1626, 7)

In [19]:
# Now we'll join these values to original x_train and x_test using hstack()
# hstack() only joins numpy array so when we write 'x_train.values', it automatically converts to numpy array.

# joined_x_train = np.hstack((x_train[['brand', 'km_driven']], x_train_new))
joined_x_train = np.hstack((x_train[['brand','km_driven']].values,x_train_new))

In [20]:
joined_x_train[0]

array(['Tata', 50000, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], dtype=object)

In [21]:
joined_x_test = np.hstack((x_test[['brand', 'km_driven']].values, x_test_new))
joined_x_test[0]

array(['Renault', 100000, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], dtype=object)

# You will wonder, why didn't we directly applied OHE on Fuel and Owner and assigned it to x_train rather than performing the above steps like to convert first and then joining the other remaining columns using hstake()? Right?
# See what happens if we do so.

In [23]:
x_train = ohe.fit_transform(x_train[['fuel', 'owner']])

C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [24]:
x_train.shape

(6502, 7)

In [25]:
x_train[0]

# See here, we are getting columns created from 'Fuel' and 'Owner' columns and the rest columns are removed.
# This is the reason we always follow the above method.

array([1., 0., 0., 0., 0., 0., 0.])

In [28]:
ohe.transform(x_test[['fuel', 'owner']])[0]

array([1., 0., 0., 0., 0., 0., 1.])

brand               Skoda
km_driven          120000
fuel               Diesel
owner        Second Owner
Name: 1, dtype: object

           brand  km_driven    fuel                 owner
1290     Renault     100000  Diesel           Third Owner
5207        Tata      80000  Diesel  Fourth & Above Owner
70    Volkswagen      80000  Diesel           First Owner
2686    Mahindra     100000  Diesel          Second Owner
4103   Chevrolet      70000  Petrol           First Owner
...          ...        ...     ...                   ...
6823      Maruti      70000  Petrol          Second Owner
4786       Skoda      11000  Petrol           First Owner
2818      Maruti      42108  Petrol           First Owner
7434        Ford      56000  Diesel           First Owner
3354     Renault     100000  Diesel           First Owner

[1626 rows x 4 columns]