# Till now whatsoever method of imputation we studied, comes under `Univariate imputation`. From this session, we will learn `Multivarite imputation`.

# Difference between `Univariate and Multivariate imputation`.

`Univarriate imputation`: When we're filling missing values of any column, and to do so, we consider data of only that particular column, it is called **Univarate imputation**.<br>

`Multivariate imputation`: When we're filling missing values of any column, and to do so, we consider entire data, then this is called **Multivariate imputation**. What KNNImputer does is, it fills missing value of the raw with the value of similar raw based on similarity.

There're many methods for `Multivariate imputation`. But we'll study only two **1) KNNImputer()** and **2) IterativeImputer** .

Here, in this session, we'll learn **KNNImputer()** and in next session we'll learn **IterativeImputer()**

**Advantage and disadvantages of KNNImputer()**:<br>

* It's more accurate than other methods.
* More computation, so takes more time(**Disadvantage**)
* As we are considering the whole dataframe for imputation, we'll have to put whole training set to the server while deployment(**Disadvantage**)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('00 titanic.csv')[['Age','Pclass','Fare','Survived']]

In [3]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [4]:
(df.isnull().mean())* 100

# Age column is having missing value, so let's fill it.

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [5]:
# Train/ test split.

x = df.drop(columns = ['Survived'])
y = df['Survived']

In [6]:
x.head()

    Age  Pclass     Fare
0  22.0       3   7.2500
1  38.0       1  71.2833
2  26.0       3   7.9250
3  35.0       1  53.1000
4  35.0       3   8.0500

In [7]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test,  y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [9]:
x_train.head()

      Age  Pclass     Fare
163  17.0       3   8.6625
379  19.0       3   7.7750
191  19.0       2  13.0000
568   NaN       3   7.2292
149  42.0       2  13.0000

In [10]:
y_train.head()

163    0
379    0
191    0
568    0
149    0
Name: Survived, dtype: int64

In [11]:
# KNNImputer()

from sklearn.impute import KNNImputer

knn = KNNImputer()

# Try making changes in the parameters on KNNImputer() and see the accuracy/

'''
parameters:
1) n_neighbors: No.of neighbors to consider. (Bydefault 5)
2) add_indicator: To add missing indicator(Bydefault False). We studied this concept in our previous session.
3) weights: Weights to be calculated with formula('uniform', 'distance' or 'user defined function'. Bydefault 'uniform')
4) metric: Formula to be used('naneuclidean' or 'user defined function'. Bydefault 'naneuclidean')
'''

"\nparameters:\n1) n_neighbors: No.of neighbors to consider. (Bydefault 5)\n2) add_indicator: To add missing indicator(Bydefault False). We studied this concept in our previous session.\n3) weights: Weights to be calculated with formula('uniform', 'distance' or 'user defined function'. Bydefault 'uniform')\n4) metric: Formula to be used('naneuclidean' or 'user defined function'. Bydefault 'naneuclidean')\n"

In [12]:
# Imputing

x_train_1 = knn.fit_transform(x_train)
x_test_1 = knn.transform(x_test)

In [13]:
# Model training

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

In [14]:
lr.fit(x_train_1, y_train)

LogisticRegression()

In [15]:
pred_1 = lr.predict(x_test_1)

In [16]:
# Accuracy_score

from sklearn.metrics import accuracy_score

In [17]:
acc_1 = accuracy_score(y_test, pred_1)
acc_1

0.6368715083798883

# Change in parameter of KNNImputer()

In [18]:
knn = KNNImputer(n_neighbors = 3, weights = 'distance')

In [19]:
x_train_2 = knn.fit_transform(x_train)
x_test_2 = knn.transform(x_test)

In [20]:
lr.fit(x_train_2, y_train)

LogisticRegression()

In [21]:
pred_2 = lr.predict(x_test_2)

In [22]:
acc_2 = accuracy_score(y_test, pred_2)
acc_2

0.6368715083798883

In [23]:
knn = KNNImputer(n_neighbors = 8, weights = 'distance', add_indicator = True)

In [24]:
x_train_3 = knn.fit_transform(x_train)
x_test_3 = knn.transform(x_test)

In [25]:
lr.fit(x_train_3, y_train)

LogisticRegression()

In [26]:
pred_3 = lr.predict(x_test_3)

In [27]:
acc_3 = accuracy_score(y_test, pred_3)
acc_3

0.6368715083798883

# Try with SimpleImputer()

In [28]:
from sklearn.impute import SimpleImputer

In [29]:
si = SimpleImputer()    # 'Strategu' bydefault is mean.

In [30]:
x_train_4 = si.fit_transform(x_train)
x_test_4 = si.transform(x_test)

In [31]:
lr.fit(x_train_4, y_train)

LogisticRegression()

In [32]:
pred_4 = lr.predict(x_test_4)

In [33]:
acc_4 = accuracy_score(y_test, pred_4)
acc_4

0.6424581005586593

# SimpleImputer(add_indicator = True)

In [34]:
si = SimpleImputer(add_indicator = True)

In [35]:
x_train_5 = si.fit_transform(x_train)
x_test_5 = si.transform(x_test)

In [36]:
lr.fit(x_train_5, y_train)

LogisticRegression()

In [37]:
pred_5 = lr.predict(x_test_5)

In [38]:
acc_5 = accuracy_score(y_test, pred_5)
acc_5

0.6368715083798883

# Find the highest accuracy.

In [45]:
highest_acc = 0

In [46]:
for accuracy in acc_1, acc_2, acc_3, acc_4, acc_5:
    if accuracy > highest_acc:
        highest_acc = accuracy
        name = accuracy

print(f'Highest accuracy: {highest_acc}')

Highest accuracy: 0.6424581005586593

# Running loop for `n_neighbors`.

In [41]:
highest_acc = 0
best_n_neighbors = 0

In [42]:
for n in range(1, 11):
    knn = KNNImputer(n_neighbors = n, add_indicator = True)
    x_train_trans = knn.fit_transform(x_train)
    x_test_trans = knn.transform(x_test)

    lr.fit(x_train_trans, y_train)
    pred = lr.predict(x_test_trans)

    acc = accuracy_score(y_test, pred)

    print(f'{n}: {acc}')

    if acc > highest_acc:
        highest_acc = acc
        best_n_neighbors = n

print()
print()
print()
print(f'Highest accuracy: {highest_acc}')
print(f'Best n_neighbors: {best_n_neighbors}')

print(x_train_trans.shape)    # To check if it's adding one extra column for missing indictor or not.

1: 0.6368715083798883
2: 0.6424581005586593
3: 0.6424581005586593
4: 0.6424581005586593
5: 0.6480446927374302
6: 0.6424581005586593
7: 0.6424581005586593
8: 0.6424581005586593
9: 0.6424581005586593
10: 0.6424581005586593



Highest accuracy: 0.6480446927374302
Best n_neighbors: 5
(712, 4)

In [43]:
# Change the value of n_nneighbors and check if the above loop is giving same result or not.

knn = KNNImputer(n_neighbors = 2, add_indicator = True)
x_train_trans = knn.fit_transform(x_train)
x_test_trans = knn.transform(x_test)

lr.fit(x_train_trans, y_train)
pred = lr.predict(x_test_trans)

acc = accuracy_score(y_test, pred)
acc

0.6424581005586593

Age       141
Pclass      0
Fare        0
dtype: int64