In [23]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [24]:
lr = LinearRegression()

In [25]:
df = pd.read_csv("00 startups.csv", usecols = ['R&D Spend', 'Administration', 'Marketing Spend', 'Profit'])

df = np.round(df/10000)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
47        0.0            14.0              0.0     4.0
45        0.0            12.0              0.0     6.0
29        7.0            15.0             11.0    10.0
7        13.0            15.0             32.0    16.0
41        3.0             8.0             16.0     8.0

In [26]:
# Seperating Target variable

df = df.iloc[:, 0:-1]

In [27]:
df

    R&D Spend  Administration  Marketing Spend
47        0.0            14.0              0.0
45        0.0            12.0              0.0
29        7.0            15.0             11.0
7        13.0            15.0             32.0
41        3.0             8.0             16.0

# Function `iterative_imputation()`

In [34]:
def iterative_imputation(df, iterations):

    # Give an initial DataFrame without performing anything.
    
    df.iloc[1, 0] = np.nan
    df.iloc[3, 1] = np.nan
    df.iloc[-1, -1] = np.nan

    # Step 1: Impute all missing values with the mean of respective columns.
    mean_rd = df['R&D Spend'].mean()
    mean_add = df['Administration'].mean()
    mean_market = df['Marketing Spend'].mean()

    
    df['R&D Spend'] = df['R&D Spend'].fillna(mean_rd)
    df['Administration'] = df['Administration'].fillna(mean_add)
    df['Marketing Spend'] = df['Marketing Spend'].fillna(mean_market)

    # df_1 = df.copy()    Remove comment from this and give comment to the same code inside loop, gives same result.
    
    for i in range(iterations):
        df_1 = df.copy()
        
        # Converting R*D Spend into np.nan.
        df_1.iloc[1, 0] = np.nan
        x_1 = df_1.iloc[[0, 2, 3, 4], [1,2]]    # 'Administration' and 'Marketing Spend' as predictor variable
        y_1 = df_1.iloc[[0, 2, 3, 4], 0]      # 'R&D Spend' as target variable.
        pred_x_1 = df_1.iloc[1, 1:3].values.reshape(1, 2)    # Missing value to be predicted.
        
        lr.fit(x_1, y_1)

        # Making predicting.
        pred_value = lr.predict(pred_x_1)

        # Filling missing value with the predicted value.
        df_1.iloc[1, 0] = pred_value.round(2)


        # Converting 'Administration's column as np.nan.
        df_1.iloc[-2, -2] = np.nan

        # Spliting into x and y.
        x_1 = df_1.iloc[[0, 1, 2, 4], [0, 2]]    # 'R*D Spend' and 'Marketing Spend' as Predictor variable and
        y_1 = df_1.iloc[[0, 1, 2, 4], 1]         # 'Administration' as class variable

        pred_x_1 = df_1.iloc[3, [0, 2]]          # Missing value to be predicted.

        # Training the model
        lr.fit(x_1, y_1)

        # Prediction
        pred_value = lr.predict(pred_x_1.values.reshape(1, 2))

        # Filling missing value
        df_1.iloc[-2,  -2] = pred_value.round(2)

        # Changing 'Marketing Spend's column as np.nan
        df_1.iloc[-1, -1] = np.nan

        # Spliting into x and y
        
        x_1 = df_1.iloc[[0, 1, 2, 3], [0, 1]]    # 'R*D Spend ' and 'Administration' as predictor variable and
        y_1 = df_1.iloc[[0, 1, 2, 3], -1]        # 'Marketing Spend' as class varibale
        pred_x_1 = df_1.iloc[-1, [0, 1]].values.reshape(1, 2)    # Missing value to be predicted.

        lr.fit(x_1, y_1)
        
        # Making prediction.
        pred_value = lr.predict(pred_x_1)

        # Filling missing value
        df_1.iloc[-1, -1] = pred_value.round(2)

        print(df_1 - df)

        df = df_1.copy()

In [35]:
iterative_imputation(df, 6)

    R&D Spend  Administration  Marketing Spend
47       0.00            0.00             0.00
45      -5.75            0.00             0.00
29       0.00            0.00             0.00
7        0.00           -6.76             0.00
41       0.00            0.00            -0.33
    R&D Spend  Administration  Marketing Spend
47       0.00            0.00             0.00
45      -0.77            0.00             0.00
29       0.00            0.00             0.00
7        0.00           -2.22             0.00
41       0.00            0.00            -0.09
    R&D Spend  Administration  Marketing Spend
47        0.0            0.00             0.00
45       -0.2            0.00             0.00
29        0.0            0.00             0.00
7         0.0           -0.57             0.00
41        0.0            0.00            -0.02
    R&D Spend  Administration  Marketing Spend
47       0.00            0.00              0.0
45      -0.05            0.00              0.0
29       0.00            0.00              0.0
7        0.00           -0.13              0.0
41       0.00            0.00              0.0
    R&D Spend  Administration  Marketing Spend
47       0.00            0.00              0.0
45      -0.01            0.00              0.0
29       0.00            0.00              0.0
7        0.00           -0.01              0.0
41       0.00            0.00              0.0
    R&D Spend  Administration  Marketing Spend
47        0.0             0.0              0.0
45        0.0             0.0              0.0
29        0.0             0.0              0.0
7         0.0             0.0              0.0
41        0.0             0.0              0.0

C:\Users\jugal\AppData\Local\Temp\ipykernel_11564\2651035220.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['R&D Spend'] = df['R&D Spend'].fillna(mean_rd)
C:\Users\jugal\AppData\Local\Temp\ipykernel_11564\2651035220.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Administration'] = df['Administration'].fillna(mean_add)
C:\Users\jugal\AppData\Local\Temp\ipykernel_11564\2651035220.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Marketing Spend'] = df['Marketing Spend'].fillna(mean_market)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(