# What is `Feature Construction` and `Feature Splitting`?

1) `Feature Construction`: Constructing a whole new feature with the help of existing feature in the dataset. For example, a dataset is having features named **Height** and **Width**, then from these we can create a new feature named **Square feet**. <br>
Another example is, if a dataset is having some features as **Business_income**, **MF_income**, **Interest_income**, we create a new column named **Total_income**. This is called `Feature Construction`.

2) `Feature splitting`: Sometimes there may be more values inside one single column, in this case we split these values and assign each of them to new column. <br>
For example, there's a column named **Name** and the value is **Mr. Nikunj**, we can create two new columns named **Title** and **Name** and split this value as Mr and Nikunj. After splitting, we'll insert Mr in Title column and 'Nikunj' in Name column.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [2]:
df = pd.read_csv('00 titanic.csv', usecols = ['Age', 'Pclass', 'SibSp', 'Parch', 'Survived'])

In [3]:
df.dropna(inplace = True)

In [4]:
df.sample(10)

     Survived  Pclass    Age  SibSp  Parch
156         1       3  16.00      0      0
188         0       3  40.00      1      1
114         0       3  17.00      0      0
886         0       2  27.00      0      0
37          0       3  21.00      0      0
545         0       1  64.00      0      0
743         0       3  24.00      1      0
78          1       2   0.83      0      2
340         1       2   2.00      1      1
530         1       2   2.00      1      1

In [5]:
df.isnull().sum()

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
dtype: int64

In [6]:
x = df.drop(columns = 'Survived')
y = df.drop(x, axis = 'columns')

In [7]:
x.head()

   Pclass   Age  SibSp  Parch
0       3  22.0      1      0
1       1  38.0      1      0
2       3  26.0      0      0
3       1  35.0      1      0
4       3  35.0      0      0

In [8]:
y.head()

   Survived
0         0
1         1
2         1
3         1
4         0

In [9]:
cross_val_score(estimator = LogisticRegression(), X = x, y = y, cv = 20, scoring = 'accuracy').mean()

C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.6933333333333332

# Applying `Feature Construction`.

In [10]:
# Creating a new column named 'family' with the help of ParCh and SibSp. +1 is added bcz we're considering that particular person as well

x['Family_size'] = x['Parch'] + x['SibSp'] + 1

In [11]:
x.head()

   Pclass   Age  SibSp  Parch  Family_size
0       3  22.0      1      0            2
1       1  38.0      1      0            2
2       3  26.0      0      0            1
3       1  35.0      1      0            2
4       3  35.0      0      0            1

In [12]:
def type(num):
    if num == 1:
        return 0    # Alone
    elif num > 1 and num <= 4:
        return 1    # Small size
    else:
        return 2    # Big family

In [13]:
type(10)

2

In [14]:
# Creating a new column 'Family_type' considering the above function.

x['Family_type'] = x['Family_size'].apply(type)

In [15]:
x.head()

   Pclass   Age  SibSp  Parch  Family_size  Family_type
0       3  22.0      1      0            2            1
1       1  38.0      1      0            2            1
2       3  26.0      0      0            1            0
3       1  35.0      1      0            2            1
4       3  35.0      0      0            1            0

In [16]:
# Now when we've created a column 'Family_type' from 'Family_size' which was created from 'SibSp' and 'Parch', we can drop those columns

x.drop(columns = ['SibSp', 'Parch', 'Family_size'], inplace = True)

In [17]:
x.head()

   Pclass   Age  Family_type
0       3  22.0            1
1       1  38.0            1
2       3  26.0            0
3       1  35.0            1
4       3  35.0            0

In [18]:
cross_val_score(estimator = LogisticRegression(), X = x, y = y, cv = 20, scoring = 'accuracy').mean()

C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.7003174603174602

# Feature splitting.

In [19]:
df2 = pd.read_csv('00 titanic.csv', usecols = ['Name', 'Ticket', 'SibSp', 'Parch', 'Survived'])

In [20]:
df2.head()

,Survived,Name,SibSp,Parch,Ticket
0,0,"Braund, Mr. Owen Harris",1,0,A/5 21171
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,PC 17599
2,1,"Heikkinen, Miss. Laina",0,0,STON/O2. 3101282
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,113803
4,0,"Allen, Mr. William Henry",0,0,373450

In [21]:
df2['Name'].str.split(',')

0                             [Braund,  Mr. Owen Harris]
1      [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                              [Heikkinen,  Miss. Laina]
3        [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                            [Allen,  Mr. William Henry]
                             ...
886                             [Montvila,  Rev. Juozas]
887                      [Graham,  Miss. Margaret Edith]
888          [Johnston,  Miss. Catherine Helen "Carrie"]
889                             [Behr,  Mr. Karl Howell]
890                               [Dooley,  Mr. Patrick]
Name: Name, Length: 891, dtype: object

In [22]:
df2['Name'].str.split(',', expand = True)    # expand = True will create a dataframe

             0                                            1
0       Braund                              Mr. Owen Harris
1      Cumings   Mrs. John Bradley (Florence Briggs Thayer)
2    Heikkinen                                  Miss. Laina
3     Futrelle           Mrs. Jacques Heath (Lily May Peel)
4        Allen                            Mr. William Henry
..         ...                                          ...
886   Montvila                                  Rev. Juozas
887     Graham                         Miss. Margaret Edith
888   Johnston               Miss. Catherine Helen "Carrie"
889       Behr                              Mr. Karl Howell
890     Dooley                                  Mr. Patrick

[891 rows x 2 columns]

In [23]:
df2['Name'].str.split(',', expand = True)[0]

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: 0, Length: 891, dtype: object

In [24]:
df2['Name'].str.split(',', expand = True)[1]

0                                  Mr. Owen Harris
1       Mrs. John Bradley (Florence Briggs Thayer)
2                                      Miss. Laina
3               Mrs. Jacques Heath (Lily May Peel)
4                                Mr. William Henry
                          ...
886                                    Rev. Juozas
887                           Miss. Margaret Edith
888                 Miss. Catherine Helen "Carrie"
889                                Mr. Karl Howell
890                                    Mr. Patrick
Name: 1, Length: 891, dtype: object

In [25]:
df2['Name'].str.split(',', expand = True)[1].str.split('.', expand = True)

         0                                       1     2
0       Mr                             Owen Harris  None
1      Mrs   John Bradley (Florence Briggs Thayer)  None
2     Miss                                   Laina  None
3      Mrs           Jacques Heath (Lily May Peel)  None
4       Mr                           William Henry  None
..     ...                                     ...   ...
886    Rev                                  Juozas  None
887   Miss                          Margaret Edith  None
888   Miss                Catherine Helen "Carrie"  None
889     Mr                             Karl Howell  None
890     Mr                                 Patrick  None

[891 rows x 3 columns]

In [26]:
df2['Name'].str.split(',', expand = True)[1].str.split('.', expand = True)[0]

0         Mr
1        Mrs
2       Miss
3        Mrs
4         Mr
       ...
886      Rev
887     Miss
888     Miss
889       Mr
890       Mr
Name: 0, Length: 891, dtype: object

In [27]:
df2['Name'].str.split(',', expand = True)[1].str.split('.', expand = True)[1]

0                                 Owen Harris
1       John Bradley (Florence Briggs Thayer)
2                                       Laina
3               Jacques Heath (Lily May Peel)
4                               William Henry
                        ...
886                                    Juozas
887                            Margaret Edith
888                  Catherine Helen "Carrie"
889                               Karl Howell
890                                   Patrick
Name: 1, Length: 891, dtype: object

In [28]:
df2['Title'] = df2['Name'].str.split(',', expand = True)[1].str.split('.', expand = True)[0]

In [29]:
df2.head()

,Survived,Name,SibSp,Parch,Ticket,Title
0,0,"Braund, Mr. Owen Harris",1,0,A/5 21171,Mr
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,PC 17599,Mrs
2,1,"Heikkinen, Miss. Laina",0,0,STON/O2. 3101282,Miss
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,113803,Mrs
4,0,"Allen, Mr. William Henry",0,0,373450,Mr

In [30]:
df2.groupby('Title').mean()['Survived'].sort_values(ascending = False)

C:\Users\jugal\AppData\Local\Temp\ipykernel_12712\1461710696.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df2.groupby('Title').mean()['Survived'].sort_values(ascending = False)

Title
 the Countess    1.000000
 Mlle            1.000000
 Sir             1.000000
 Ms              1.000000
 Lady            1.000000
 Mme             1.000000
 Mrs             0.792000
 Miss            0.697802
 Master          0.575000
 Col             0.500000
 Major           0.500000
 Dr              0.428571
 Mr              0.156673
 Jonkheer        0.000000
 Rev             0.000000
 Don             0.000000
 Capt            0.000000
Name: Survived, dtype: float64

In [32]:
df2[df2['Title'] == ' Mrs']

,Survived,Name,SibSp,Parch,Ticket,Title
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,PC 17599,Mrs
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,113803,Mrs
8,1,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",0,2,347742,Mrs
9,1,"Nasser, Mrs. Nicholas (Adele Achem)",1,0,237736,Mrs
15,1,"Hewlett, Mrs. (Mary D Kingcome)",0,0,248706,Mrs
...,...,...,...,...,...,...
871,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,1,11751,Mrs
874,1,"Abelson, Mrs. Samuel (Hannah Wizosky)",1,0,P/PP 3381,Mrs
879,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",0,1,11767,Mrs
880,1,"Shelley, Mrs. William (Imanita Parrish Hall)",0,1,230433,Mrs
885,0,"Rice, Mrs. William (Margaret Norton)",0,5,382652,Mrs

In [33]:
# There're trailing space before values in 'Title' column, so removing it.

df2['Title'] = df2['Title'].str.strip()

In [34]:
df2[df2.Title == 'Mrs'].head()

,Survived,Name,SibSp,Parch,Ticket,Title
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,PC 17599,Mrs
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,113803,Mrs
8,1,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",0,2,347742,Mrs
9,1,"Nasser, Mrs. Nicholas (Adele Achem)",1,0,237736,Mrs
15,1,"Hewlett, Mrs. (Mary D Kingcome)",0,0,248706,Mrs

In [35]:
df2['Is_Married'] = 0
df2['Is_Married'].loc[df2['Title'] == 'Mrs'] = 1

C:\Users\jugal\AppData\Local\Temp\ipykernel_12712\359320749.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Is_Married'].loc[df2['Title'] == 'Mrs'] = 1

In [36]:
df2.head()

,Survived,Name,SibSp,Parch,Ticket,Title,Is_Married
0,0,"Braund, Mr. Owen Harris",1,0,A/5 21171,Mr,0
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,PC 17599,Mrs,1
2,1,"Heikkinen, Miss. Laina",0,0,STON/O2. 3101282,Miss,0
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,113803,Mrs,1
4,0,"Allen, Mr. William Henry",0,0,373450,Mr,0