## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'00 Fifa Worldcup 2022.csv')

df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


    
**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

# Q-2: Find out how many matches the teams played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.
Note: The DataFrame.rank() method takes an optiinal parameter named method. This parameter takes different values, but one of them is average which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as first, then you will get in integers but the datatype will be float. So, try with method="first" parameter.

In [3]:
team = df['Team'].value_counts()
against = df['Against'].value_counts()
#against

matches_played = (team + against).sort_values(ascending = False)

matches_played

Argentina         14.0
Croatia           14.0
Morocco           14.0
France            13.0
Brazil            10.0
Portugal          10.0
England           10.0
Netherlands       10.0
Japan              8.0
United States      8.0
Switzerland        8.0
Spain              8.0
Senegal            8.0
Poland             8.0
Australia          8.0
Korea Republic     8.0
Iran               6.0
Mexico             6.0
Ghana              6.0
Germany            6.0
Ecuador            6.0
Denmark            6.0
Qatar              6.0
Saudi Arabia       6.0
Costa Rica         6.0
Serbia             6.0
Canada             6.0
Cameroon           6.0
Tunisia            6.0
Belgium            6.0
Uruguay            6.0
Wales              6.0
Fram               NaN
Name: count, dtype: float64

In [4]:
matches_played = matches_played.to_frame()  # to_frame() converts Series to DAtaFrame

In [5]:
matches_played

                count
Argentina        14.0
Croatia          14.0
Morocco          14.0
France           13.0
Brazil           10.0
Portugal         10.0
England          10.0
Netherlands      10.0
Japan             8.0
United States     8.0
Switzerland       8.0
Spain             8.0
Senegal           8.0
Poland            8.0
Australia         8.0
Korea Republic    8.0
Iran              6.0
Mexico            6.0
Ghana             6.0
Germany           6.0
Ecuador           6.0
Denmark           6.0
Qatar             6.0
Saudi Arabia      6.0
Costa Rica        6.0
Serbia            6.0
Canada            6.0
Cameroon          6.0
Tunisia           6.0
Belgium           6.0
Uruguay           6.0
Wales             6.0
Fram              NaN

In [6]:
matches_played.rename(columns = {0: 'matches_played'}, inplace = True)


matches_played

                count
Argentina        14.0
Croatia          14.0
Morocco          14.0
France           13.0
Brazil           10.0
Portugal         10.0
England          10.0
Netherlands      10.0
Japan             8.0
United States     8.0
Switzerland       8.0
Spain             8.0
Senegal           8.0
Poland            8.0
Australia         8.0
Korea Republic    8.0
Iran              6.0
Mexico            6.0
Ghana             6.0
Germany           6.0
Ecuador           6.0
Denmark           6.0
Qatar             6.0
Saudi Arabia      6.0
Costa Rica        6.0
Serbia            6.0
Canada            6.0
Cameroon          6.0
Tunisia           6.0
Belgium           6.0
Uruguay           6.0
Wales             6.0
Fram              NaN

In [7]:
matches_played['rank'] = matches_played.rank(method = 'first', ascending = False)

# Ascending = False. Bcz by-default it assigns the highest rank to the lowest number and vice-versa

matches_played.sort_values(by = 'rank')

                count  rank
Argentina        14.0   1.0
Croatia          14.0   2.0
Morocco          14.0   3.0
France           13.0   4.0
Brazil           10.0   5.0
Portugal         10.0   6.0
England          10.0   7.0
Netherlands      10.0   8.0
Japan             8.0   9.0
United States     8.0  10.0
Switzerland       8.0  11.0
Spain             8.0  12.0
Senegal           8.0  13.0
Poland            8.0  14.0
Australia         8.0  15.0
Korea Republic    8.0  16.0
Iran              6.0  17.0
Mexico            6.0  18.0
Ghana             6.0  19.0
Germany           6.0  20.0
Ecuador           6.0  21.0
Denmark           6.0  22.0
Qatar             6.0  23.0
Saudi Arabia      6.0  24.0
Costa Rica        6.0  25.0
Serbia            6.0  26.0
Canada            6.0  27.0
Cameroon          6.0  28.0
Tunisia           6.0  29.0
Belgium           6.0  30.0
Uruguay           6.0  31.0
Wales             6.0  32.0
Fram              NaN   NaN

method parameter can be 'average(by-default, first, min, max, dense'.
------------------------------------

Original Data

Number
1
2
4
4
5
-------------------------------------

method = 'average' (by-default)

But as there are two 4s, rank will be (Rank 3 + Rank 4)/2 = 7/2 = 3.5
So the true ranks will be

Number    Rank
1          1 
2          2 
4          3.5
4          3.5
5          5
------------------------------------

method = 'min'. All equal values are assigned the minimum rank.

Number    Rank
1          1 
2          2 
4          3
4          3
5          5
------------------------------------

method = 'max'. All equal values are assigned the maximum rank.

Number    Rank
1          1 
2          2 
4          4
4          4
5          5
------------------------------------
method = 'first'. All equal values are ranked in the order they appear in the DataFrame. Means the rank is continuous

Number    Rank
1          1 
2          2 
4          3
4          4
5          5
------------------------------------
method = 'dense'.  Like 'min' but ranks are consecutive, means it doesn't leave gap.


Number    Rank
1          1 
2          2 
4          3
4          3
5          4

In [8]:
matches_played.index.name = 'team'

matches_played

# matches_played.index.name is used to set name of the index column

                count  rank
team
Argentina        14.0   1.0
Croatia          14.0   2.0
Morocco          14.0   3.0
France           13.0   4.0
Brazil           10.0   5.0
Portugal         10.0   6.0
England          10.0   7.0
Netherlands      10.0   8.0
Japan             8.0   9.0
United States     8.0  10.0
Switzerland       8.0  11.0
Spain             8.0  12.0
Senegal           8.0  13.0
Poland            8.0  14.0
Australia         8.0  15.0
Korea Republic    8.0  16.0
Iran              6.0  17.0
Mexico            6.0  18.0
Ghana             6.0  19.0
Germany           6.0  20.0
Ecuador           6.0  21.0
Denmark           6.0  22.0
Qatar             6.0  23.0
Saudi Arabia      6.0  24.0
Costa Rica        6.0  25.0
Serbia            6.0  26.0
Canada            6.0  27.0
Cameroon          6.0  28.0
Tunisia           6.0  29.0
Belgium           6.0  30.0
Uruguay           6.0  31.0
Wales             6.0  32.0
Fram              NaN   NaN

In [9]:
matches_played.index.name

'team'

# Question-3: Find out these below topics:

1) The information about the Fifa worldcup dataset.
3) The description about the Fifa worldcup dataset
4) Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
5) Drop all the duplicate rows permanently.
6) Drop the columns: `"Sl No", "Match No.", "Red Cards" and "Pts" permanently.`ntly.

In [10]:
# 1) The information about the Fifa worldcup dataset.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB

In [11]:
# 2) The description about the Fifa worldcup dataset

df.describe()

,Sl. No,Match No.,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,...,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,64.500000,32.500000,1.343750,43.476562,1.203125,0.117188,0.914062,11.257812,4.007812,4.835938,...,12.320312,1.976562,502.859375,430.929688,19.523438,4.898438,4.468750,14.250000,0.335938,1.429688
std,37.094474,18.545539,1.342448,11.442403,1.324270,0.322907,1.150333,5.406683,2.588576,2.610630,...,4.691983,1.731891,160.160487,160.893724,8.596799,3.520111,2.774852,4.712189,0.941412,1.389973
min,1.000000,1.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,225.000000,156.000000,4.000000,0.000000,0.000000,5.000000,0.000000,0.000000
25%,32.750000,16.750000,0.000000,35.000000,0.000000,0.000000,0.000000,7.750000,2.000000,3.000000,...,9.000000,1.000000,398.250000,323.250000,13.000000,3.000000,2.000000,11.000000,0.000000,0.000000
50%,64.500000,32.500000,1.000000,45.000000,1.000000,0.000000,1.000000,10.000000,4.000000,4.000000,...,12.000000,2.000000,495.500000,419.000000,19.000000,4.000000,4.000000,14.000000,0.000000,1.000000
75%,96.250000,48.250000,2.000000,51.000000,2.000000,0.000000,1.000000,14.000000,6.000000,6.000000,...,15.000000,3.000000,589.500000,519.750000,24.000000,6.000000,6.000000,17.000000,0.000000,3.000000
max,128.000000,64.000000,7.000000,78.000000,7.000000,1.000000,6.000000,32.000000,13.000000,17.000000,...,30.000000,10.000000,1070.000000,994.000000,53.000000,25.000000,14.000000,30.000000,5.000000,3.000000

In [12]:
# 3) Check is there any missing values, if there is any missing values, 
# fill those values with the average value for that particular column.


df.isnull().sum()

# There're no missing values in any column

Sl. No                             0
Match No.                          0
Team                               0
Against                            0
Group                              0
Goal                               0
Possession (%)                     0
Inside Penalty Area                0
Outside Penalty Area               0
Assists                            0
Total Attempts                     0
On Target                          0
Off Target                         0
Target in Penalty                  0
Target from Outside                0
Left Channel                       0
Left Inside Channel                0
Central Channel                    0
Right Inside Channel               0
Right Channel                      0
Receptions MD                      0
Receptions D                       0
Attempted Line Breaks              0
Completed Line Breaks              0
Attempted Defensive Line Breaks    0
Completed Defensive Line Breaks    0
Yellow Cards                       0
Red Cards                          0
Fouls Against                      0
Offsides                           0
Passes                             0
Passes Completed                   0
Crosses                            0
Crosses Completed                  0
Corners                            0
Free Kicks                         0
Penalties Scored                   0
Pts                                0
dtype: int64

In [13]:
# 4) Drop all the duplicate rows permanently.

# Fetching the duplicate rows

df[df.duplicated()]

# There are no duplicate rows
# Dropping the duplicate rows. (Just for the practice)

df.drop_duplicates(inplace = True)

df.duplicated().sum()

0

In [14]:
# 5) Drop the columns: "Sl. No", "Match No.", "Red Cards" and "Pts" permanently.

df.drop(['Sl. No', 'Match No.', 'Red Cards', 'Pts'], axis = 'columns', inplace = True)

In [15]:
df

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,...,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
0,Qatar,Ecuador,A,0,40,0,0,0,5,0,...,4,15,3,453,387,10,5,1,19,0
1,Ecuador,Qatar,A,2,46,2,0,1,5,5,...,2,15,4,484,419,26,10,3,17,1
2,England,Iran,B,6,69,6,0,6,13,7,...,0,9,2,810,733,29,9,8,16,0
3,Iran,England,B,2,20,2,0,1,8,3,...,2,14,2,232,156,11,3,0,10,1
4,Senegal,Netherlands,A,0,39,0,0,0,15,4,...,2,13,2,391,326,22,8,6,14,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,Morocco,Fram,F,0,55,0,0,0,13,1,...,1,11,3,583,518,22,1,3,15,0
124,Croatia,Morocco,F,2,45,2,0,2,14,4,...,0,13,2,491,430,21,3,6,13,0
125,Morocco,Croatia,F,1,45,1,0,0,7,2,...,2,11,2,494,428,20,5,3,15,0
126,Argentina,France,C,3,46,3,0,1,21,9,...,4,26,4,648,544,20,4,6,22,5
127,France,Argentina,D,3,40,3,0,1,10,5,...,3,19,4,516,419,24,3,5,28,4

In [16]:
df.columns

Index(['Team', 'Against', 'Group', 'Goal', 'Possession (%)',
       'Inside Penalty Area', 'Outside Penalty Area', 'Assists',
       'Total Attempts', 'On Target', 'Off Target', 'Target in Penalty',
       'Target from Outside', 'Left Channel', 'Left Inside Channel',
       'Central Channel', 'Right Inside Channel', 'Right Channel',
       'Receptions MD', 'Receptions D', 'Attempted Line Breaks',
       'Completed Line Breaks', 'Attempted Defensive Line Breaks',
       'Completed Defensive Line Breaks', 'Yellow Cards', 'Fouls Against',
       'Offsides', 'Passes', 'Passes Completed', 'Crosses',
       'Crosses Completed', 'Corners', 'Free Kicks', 'Penalties Scored'],
      dtype='object')

# `Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [17]:
# 1) Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".

df['Rank'] = df['Team'].rank(method = 'dense')
#metod = 'dense' bcz it will give same rank to the duplicate teams and also the numbers will be continuous.

df.head()

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Rank
0,Qatar,Ecuador,A,0,40,0,0,0,5,0,...,15,3,453,387,10,5,1,19,0,23.0
1,Ecuador,Qatar,A,2,46,2,0,1,5,5,...,15,4,484,419,26,10,3,17,1,10.0
2,England,Iran,B,6,69,6,0,6,13,7,...,9,2,810,733,29,9,8,16,0,11.0
3,Iran,England,B,2,20,2,0,1,8,3,...,14,2,232,156,11,3,0,10,1,15.0
4,Senegal,Netherlands,A,0,39,0,0,0,15,4,...,13,2,391,326,22,8,6,14,0,25.0

In [18]:
# 2) Change the datatype of this column to integer by using np.int16

df['Rank'] = df['Rank'].astype('int16')

df.Rank.dtype

dtype('int16')

In [19]:
# 3) Set the index of the DataFrame by using this "Rank" column permanently.

df.set_index('Rank', inplace = True)

df.head()

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,...,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
Rank,,,,,,,,,,,,,,,,,,,,,
23,Qatar,Ecuador,A,0,40,0,0,0,5,0,...,4,15,3,453,387,10,5,1,19,0
10,Ecuador,Qatar,A,2,46,2,0,1,5,5,...,2,15,4,484,419,26,10,3,17,1
11,England,Iran,B,6,69,6,0,6,13,7,...,0,9,2,810,733,29,9,8,16,0
15,Iran,England,B,2,20,2,0,1,8,3,...,2,14,2,232,156,11,3,0,10,1
25,Senegal,Netherlands,A,0,39,0,0,0,15,4,...,2,13,2,391,326,22,8,6,14,0

In [20]:
# 4) After that, sort the dataframe based on the "Rank" index.

df.sort_index()

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,...,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
Rank,,,,,,,,,,,,,,,,,,,,,
1,Argentina,Mexico,C,2,50,1,1,2,5,2,...,1,15,2,533,464,14,2,4,23,0
1,Argentina,Netherlands,C,2,44,2,0,1,15,6,...,8,18,2,603,511,16,4,8,30,5
1,Argentina,Saudi Arabia,C,1,51,1,0,0,14,6,...,0,7,10,593,525,36,15,9,21,1
1,Argentina,France,C,3,46,3,0,1,21,9,...,4,26,4,648,544,20,4,6,22,5
1,Argentina,Croatia,C,3,34,3,0,1,10,7,...,2,15,1,408,344,8,2,2,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,Uruguay,Ghana,H,2,39,2,0,1,12,7,...,3,11,2,446,361,15,4,2,20,0
31,Uruguay,Portugal,H,0,35,0,0,0,10,3,...,2,16,0,390,306,18,5,2,13,0
32,Wales,Iran,B,0,51,0,0,0,10,3,...,1,9,2,508,413,20,5,2,12,0
32,Wales,England,B,0,33,0,0,0,7,1,...,2,16,1,325,261,4,1,1,10,0
32,Wales,United States,B,1,39,1,0,0,7,3,...,2,10,1,409,321,15,6,3,15,1

# Questions on IPL's dataset

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

In [21]:
ipl = pd.read_csv(r'00 ipl_2008_2022.csv')

ipl.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [22]:
ipl.Team1.value_counts()

Team1
Royal Challengers Bangalore    126
Mumbai Indians                 112
Chennai Super Kings            111
Kolkata Knight Riders          105
Kings XI Punjab                 92
Rajasthan Royals                89
Delhi Daredevils                85
Sunrisers Hyderabad             69
Deccan Chargers                 39
Delhi Capitals                  29
Pune Warriors                   23
Punjab Kings                    18
Gujarat Lions                   16
Lucknow Super Giants             8
Gujarat Titans                   7
Rising Pune Supergiant           7
Rising Pune Supergiants          7
Kochi Tuskers Kerala             7
Name: count, dtype: int64

In [23]:
# Replacing teams with their current names

data = {
    'Kings XI Punjab': 'Punjab Kings',
    'Delhi Daredevils': 'Delhi Capitals',
    'Deccan Chargers': 'Sunrisers Hyderabad',
    'Gujarat Titans': 'Gujarat Lions',
    'Pune Warriors': 'Rising Pune Supergiants',
    'Rising Pune Supergiant': "Rising Pune Supergiants"
}

ipl.Team1.replace(data, inplace = True)
ipl.Team2.replace(data, inplace = True)
ipl.WinningTeam.replace(data, inplace = True)

ipl.Team1.value_counts() + ipl.Team2.value_counts()

Chennai Super Kings            208
Delhi Capitals                 224
Gujarat Lions                   46
Kochi Tuskers Kerala            14
Kolkata Knight Riders          223
Lucknow Super Giants            15
Mumbai Indians                 231
Punjab Kings                   218
Rajasthan Royals               192
Rising Pune Supergiants         76
Royal Challengers Bangalore    226
Sunrisers Hyderabad            227
Name: count, dtype: int64

In [24]:
ipl.isnull().sum()

ID                   0
City                51
Date                 0
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

In [25]:
# Removing rows of WinningTean column

ipl.dropna(subset = 'WinningTeam', inplace = True)

ipl.WinningTeam.isnull().sum()

0

# `Question:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [26]:
ipl.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Lions,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Lions,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Lions,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Lions,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [27]:
ipl.dtypes

ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [28]:
final_matches = ipl[ipl['MatchNumber'] == 'Final']

final_matches    # This df contains all the final matches

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Lions,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Lions,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
74,1254117,Dubai,2021-10-15,2021,Final,Chennai Super Kings,Kolkata Knight Riders,Dubai International Cricket Stadium,Kolkata Knight Riders,field,N,Chennai Super Kings,Runs,27.0,NaN,F du Plessis,"['RD Gaikwad', 'F du Plessis', 'RV Uthappa', '...","['Shubman Gill', 'VR Iyer', 'N Rana', 'SP Nari...",Nitin Menon,RK Illingworth
134,1237181,NaN,2020-11-10,2020/21,Final,Delhi Capitals,Mumbai Indians,Dubai International Cricket Stadium,Delhi Capitals,bat,N,Mumbai Indians,Wickets,5.0,NaN,TA Boult,"['MP Stoinis', 'S Dhawan', 'AM Rahane', 'SS Iy...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",CB Gaffaney,Nitin Menon
194,1181768,Hyderabad,2019-05-12,2019,Final,Mumbai Indians,Chennai Super Kings,Rajiv Gandhi International Stadium,Mumbai Indians,bat,N,Mumbai Indians,Runs,1.0,NaN,JJ Bumrah,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['F du Plessis', 'SR Watson', 'SK Raina', 'AT ...",IJ Gould,Nitin Menon
254,1136620,Mumbai,2018-05-27,2018,Final,Sunrisers Hyderabad,Chennai Super Kings,Wankhede Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,8.0,NaN,SR Watson,"['SP Goswami', 'S Dhawan', 'KS Williamson', 'S...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...",M Erasmus,S Ravi
314,1082650,Hyderabad,2017-05-21,2017,Final,Mumbai Indians,Rising Pune Supergiants,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,bat,N,Mumbai Indians,Runs,1.0,NaN,KH Pandya,"['LMP Simmons', 'PA Patel', 'AT Rayudu', 'RG S...","['AM Rahane', 'RA Tripathi', 'SPD Smith', 'MS ...",NJ Llong,S Ravi
373,981019,Bangalore,2016-05-29,2016,Final,Royal Challengers Bangalore,Sunrisers Hyderabad,M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,N,Sunrisers Hyderabad,Runs,8.0,NaN,BCJ Cutting,"['CH Gayle', 'V Kohli', 'AB de Villiers', 'KL ...","['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...",HDPK Dharmasena,BNJ Oxenford
433,829823,Kolkata,2015-05-24,2015,Final,Mumbai Indians,Chennai Super Kings,Eden Gardens,Chennai Super Kings,field,N,Mumbai Indians,Runs,41.0,NaN,RG Sharma,"['LMP Simmons', 'PA Patel', 'RG Sharma', 'KA P...","['DR Smith', 'MEK Hussey', 'SK Raina', 'MS Dho...",HDPK Dharmasena,RK Illingworth
492,734049,Bangalore,2014-06-01,2014,Final,Kolkata Knight Riders,Punjab Kings,M Chinnaswamy Stadium,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,3.0,NaN,MK Pandey,"['RV Uthappa', 'G Gambhir', 'MK Pandey', 'YK P...","['V Sehwag', 'M Vohra', 'GJ Bailey', 'WP Saha'...",HDPK Dharmasena,BNJ Oxenford
552,598073,Kolkata,2013-05-26,2013,Final,Chennai Super Kings,Mumbai Indians,Eden Gardens,Mumbai Indians,bat,N,Mumbai Indians,Runs,23.0,NaN,KA Pollard,"['MEK Hussey', 'M Vijay', 'SK Raina', 'S Badri...","['DR Smith', 'AP Tare', 'KD Karthik', 'RG Shar...",HDPK Dharmasena,SJA Taufel
628,548381,Chennai,2012-05-27,2012,Final,Kolkata Knight Riders,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,MS Bisla,"['MS Bisla', 'G Gambhir', 'JH Kallis', 'LR Shu...","['MEK Hussey', 'M Vijay', 'SK Raina', 'MS Dhon...",BF Bowden,SJA Taufel
702,501271,Chennai,2011-05-28,2011,Final,Chennai Super Kings,Royal Challengers Bangalore,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,58.0,NaN,M Vijay,"['MEK Hussey', 'M Vijay', 'MS Dhoni', 'SK Rain...","['MA Agarwal', 'CH Gayle', 'V Kohli', 'AB de V...",Asad Rauf,SJA Taufel
775,419165,Mumbai,2010-04-25,2009/10,Final,Chennai Super Kings,Mumbai Indians,Dr DY Patil Sports Academy,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,22.0,NaN,SK Raina,"['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...","['S Dhawan', 'SR Tendulkar', 'AM Nayar', 'Harb...",RE Koertzen,SJA Taufel
835,392239,Johannesburg,2009-05-24,2009,Final,Royal Challengers Bangalore,Sunrisers Hyderabad,New Wanderers Stadium,Royal Challengers Bangalore,field,N,Sunrisers Hyderabad,Runs,6.0,NaN,A Kumble,"['JH Kallis', 'MK Pandey', 'RE van der Merwe',...","['AC Gilchrist', 'HH Gibbs', 'TL Suman', 'A Sy...",RE Koertzen,SJA Taufel
892,336040,Mumbai,2008-06-01,2007/08,Final,Chennai Super Kings,Rajasthan Royals,Dr DY Patil Sports Academy,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,3.0,NaN,YK Pathan,"['PA Patel', 'S Vidyut', 'SK Raina', 'JA Morke...","['NK Patel', 'SA Asnodkar', 'Kamran Akmal', 'S...",BF Bowden,RE Koertzen

In [29]:
# Creating a new column 'AllPlayers' containg all 24 players of both the teams

final_matches['AllPlayers'] = (final_matches['Team1Players'] + final_matches['Team2Players'])

final_matches.loc[0]['AllPlayers']   

# AllPlayers columns as all the players of Team1 and Team 2 of all final matches

C:\Users\jugal\AppData\Local\Temp\ipykernel_19064\4079715021.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_matches['AllPlayers'] = (final_matches['Team1Players'] + final_matches['Team2Players'])

"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Ashwin', 'R Parag', 'TA Boult', 'OC McCoy', 'M Prasidh Krishna', 'YS Chahal']['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']"

In [30]:
# Confirming If the result is correct or not
final_matches.iloc[[0]] ['Team1Players'].to_list()

["['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Ashwin', 'R Parag', 'TA Boult', 'OC McCoy', 'M Prasidh Krishna', 'YS Chahal']"]

In [31]:
final_matches.iloc[[0]] ['Team2Players'].to_list()

["['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']"]

In [32]:
all_players = final_matches['AllPlayers'].str.split(',')

all_players

# split(',') will split AllPlayers columns from ',' and will create a list of all players.

0      [['YBK Jaiswal',  'JC Buttler',  'SV Samson', ...
74     [['RD Gaikwad',  'F du Plessis',  'RV Uthappa'...
134    [['MP Stoinis',  'S Dhawan',  'AM Rahane',  'S...
194    [['Q de Kock',  'RG Sharma',  'SA Yadav',  'Is...
254    [['SP Goswami',  'S Dhawan',  'KS Williamson',...
314    [['LMP Simmons',  'PA Patel',  'AT Rayudu',  '...
373    [['CH Gayle',  'V Kohli',  'AB de Villiers',  ...
433    [['LMP Simmons',  'PA Patel',  'RG Sharma',  '...
492    [['RV Uthappa',  'G Gambhir',  'MK Pandey',  '...
552    [['MEK Hussey',  'M Vijay',  'SK Raina',  'S B...
628    [['MS Bisla',  'G Gambhir',  'JH Kallis',  'LR...
702    [['MEK Hussey',  'M Vijay',  'MS Dhoni',  'SK ...
775    [['M Vijay',  'ML Hayden',  'SK Raina',  'S Ba...
835    [['JH Kallis',  'MK Pandey',  'RE van der Merw...
892    [['PA Patel',  'S Vidyut',  'SK Raina',  'JA M...
Name: AllPlayers, dtype: object

In [33]:
all_players.explode()

# explode will create a new row for each player

0        ['YBK Jaiswal'
0          'JC Buttler'
0           'SV Samson'
0          'D Padikkal'
0          'SO Hetmyer'
             ...
892         'RA Jadeja'
892          'SK Warne'
892     'Sohail Tanvir'
892        'SK Trivedi'
892         'MM Patel']
Name: AllPlayers, Length: 315, dtype: object

In [34]:
all_players = all_players.explode(ignore_index = True)

all_players

# ignore_index = False will give continuous index
# in the above code index was same

0        ['YBK Jaiswal'
1          'JC Buttler'
2           'SV Samson'
3          'D Padikkal'
4          'SO Hetmyer'
             ...
310         'RA Jadeja'
311          'SK Warne'
312     'Sohail Tanvir'
313        'SK Trivedi'
314         'MM Patel']
Name: AllPlayers, Length: 315, dtype: object

In [35]:
matches_played = all_players.value_counts()
matches_played

# Hence, Dhoni played most no_of_final matches in ipl, that is 10

AllPlayers
 'MS Dhoni'       10
 'SK Raina'        8
 'DJ Bravo'        7
 'RA Jadeja'       7
 'AT Rayudu'       7
                  ..
['CH Gayle'        1
 'KL Rahul'        1
 'Sachin Baby'     1
 'STR Binny'       1
 'MM Patel']       1
Name: count, Length: 191, dtype: int64

In [36]:
matches_played.idxmax()

" 'MS Dhoni'"

# `Question:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in descendng order of points and in ascending order of team name.

For winning - 2 Points<br>
For loosing - 0 Point<br>
For not result both team gets 1 points.    `Here there are no matches with no-result`

Make dataframe which will have
`TeamName`, `MatchesPlayed`, `MatchesWon`, `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```



# Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

# `Remember: Season column is string.`

In [37]:
def point_table(ipl, season):
    
    subset = ipl[ipl['Season'] == str(season)]    # This code will fetch the records of passed season

    matches_won = subset['WinningTeam'].value_counts()    # This code will return matches won by each team

############################################################################

    # Names of the first two teams
    
    team_1 = matches_won.index[0]    # Name of 1st team with maximum winnings
    team_2 = matches_won.index[1]    # Name of 2nd team with maximum winnings

############################################################################

    # Total matches won by First 2 teams

    team_1st_total_winning = matches_won[0]
    team_2nd_total_winning = matches_won[1]

############################################################################

    # Total points of first 2 teams
    
    team_1st_points = subset[subset['WinningTeam'] == team_1].shape[0]*2   # Returns the no_of points by team 1
    team_2nd_points = subset[subset['WinningTeam'] == team_2].shape[0]*2   # Returns the no_of points by team 2
    
############################################################################

    # Total no_of_matches played by first two teams
    
    total_matches_team_1 = subset[    # Total no_of_matches played by 1st team
    (subset['Team1'] == team_1) |
    (subset['Team2'] == team_1)
    ].shape[0]

    total_matches_team_2 = subset[    # Total no_of_matches played by 1st team
    (subset['Team1'] == team_2) |
    (subset['Team2'] == team_2)
    ].shape[0]

############################################################################
    
    # Creating the final dataframe

    data = {'Team': [team_1, team_2],
           'Total Matches Played': [total_matches_team_1, total_matches_team_2],
            'Winnings': [team_1st_total_winning, team_2nd_total_winning],
            'Points': [team_1st_points, team_2nd_points],
            'Season': season
           }
    
    df = pd.DataFrame(data)
    
    return df.set_index('Team')

In [39]:
point_table(ipl, 2019)

C:\Users\jugal\AppData\Local\Temp\ipykernel_19064\4191470423.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team_1st_total_winning = matches_won[0]
C:\Users\jugal\AppData\Local\Temp\ipykernel_19064\4191470423.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team_2nd_total_winning = matches_won[1]

                     Total Matches Played  Winnings  Points  Season
Team
Mumbai Indians                         16        11      22    2019
Chennai Super Kings                    17        10      20    2019

# Complete