In [1]:
import pandas as pd
import numpy as np

In [25]:
df = pd.read_csv(r"00 Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [26]:
x = df[['Age', 'EstimatedSalary']]
y = df['Purchased']

In [27]:
x

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [28]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [29]:
# Train Test Split
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2, 
    random_state=1)

In [31]:
x_train

     Age  EstimatedSalary
93    29            28000
23    45            22000
299   46           117000
13    32            18000
90    22            81000
..   ...              ...
255   52            90000
72    20            23000
396   51            23000
235   46            79000
37    30            49000

[320 rows x 2 columns]

In [32]:
y_train

93     0
23     1
299    1
13     0
90     0
      ..
255    1
72     0
396    1
235    1
37     0
Name: Purchased, Length: 320, dtype: int64

In [33]:
# Standardization

from sklearn.preprocessing import StandardScaler

In [34]:
ss = StandardScaler().set_output(transform='pandas')

In [35]:
x_train_scaled = ss.fit_transform(x_train)
x_test_scaled = ss.transform(x_test)

In [36]:
x_train_scaled

          Age  EstimatedSalary
93  -0.803301        -1.191218
23   0.756980        -1.368598
299  0.854498         1.439920
13  -0.510748        -1.486851
90  -1.485924         0.375639
..        ...              ...
255  1.439603         0.641709
72  -1.680959        -1.339035
396  1.342085        -1.339035
235  0.854498         0.316513
37  -0.705783        -0.570388

[320 rows x 2 columns]

In [37]:
x_train.describe()

              Age  EstimatedSalary
count  320.000000       320.000000
mean    37.237500     68293.750000
std     10.270625     33878.650655
min     18.000000     15000.000000
25%     29.000000     43000.000000
50%     37.000000     65000.000000
75%     45.000000     85250.000000
max     60.000000    150000.000000

In [38]:
x_train_scaled.describe()

                Age  EstimatedSalary
count  3.200000e+02     3.200000e+02
mean   2.664535e-16     6.938894e-18
std    1.001566e+00     1.001566e+00
min   -1.875994e+00    -1.575541e+00
25%   -8.033008e-01    -7.477678e-01
50%   -2.316042e-02    -9.737426e-02
75%    7.569800e-01     5.012834e-01
max    2.219743e+00     2.415510e+00