In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.float_format', '{:.2f}'.format)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.width', None)

np.set_printoptions(suppress=True, precision=2)

In [2]:
imdb = pd.read_csv(r"00 imdb_dataset.csv")

imdb.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.30,Frank Darabont,Tim Robbins,2343110,28341469.00,80.00
1,The Godfather,1972,175,Crime,9.20,Francis Ford Coppola,Marlon Brando,1620367,134966411.00,100.00
2,The Dark Knight,2008,152,Action,9.00,Christopher Nolan,Christian Bale,2303232,534858444.00,84.00
3,The Godfather: Part II,1974,202,Crime,9.00,Francis Ford Coppola,Al Pacino,1129952,57300000.00,90.00
4,12 Angry Men,1957,96,Crime,9.00,Sidney Lumet,Henry Fonda,689845,4360000.00,96.00

In [3]:
genres = imdb.groupby('Genre')    # Returns group-by object
genres

In [4]:
genres.sum(numeric_only = True)    # Sums all numeric columns for each group

           Runtime  IMDB_Rating  No_of_Votes          Gross  Metascore
Genre
Action       22196      1367.30     72282412 32632261314.00   10499.00
Adventure     9656       571.50     22576163  9496922464.00    5020.00
Animation     8166       650.30     21978630 14631473048.00    6082.00
Biography    11970       698.60     24006844  8276357606.00    6023.00
Comedy       17380      1224.70     27620327 15663868165.00    9840.00
Crime        13524       857.80     33533615  8452631908.00    6706.00
Drama        36049      2299.70     61367304 35409974041.00   19208.00
Family         215        15.60       551221   439110554.00     158.00
Fantasy        170        16.00       146222   782726696.00       0.00
Film-Noir      312        23.90       367215   125910543.00     287.00
Horror        1123        87.00      3742556  1034649238.00     880.00
Mystery       1429        95.70      4203004  1256417015.00     633.00
Thriller       108         7.80        27733    17550741.00      81.00
Western        593        33.40      1289665    58221508.00     313.00

In [5]:
imdb[imdb['Genre'] == 'Action'] ["Runtime"].sum()   # Same as above

22196

In [6]:
genres.min()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.60,Abhishek Chaubey,Aamir Khan,25312,3296.00,33.00
Adventure,2001: A Space Odyssey,1925,88,7.60,Akira Kurosawa,Aamir Khan,29999,61001.00,41.00
Animation,Akira,1940,71,7.60,Adam Elliot,Adrian Molina,25229,128985.00,61.00
Biography,12 Years a Slave,1928,93,7.60,Adam McKay,Adrien Brody,27254,21877.00,48.00
Comedy,(500) Days of Summer,1921,68,7.60,Alejandro G. Iñárritu,Aamir Khan,26337,1305.00,45.00
Crime,12 Angry Men,1931,80,7.60,Akira Kurosawa,Ajay Devgn,27712,6013.00,47.00
Drama,1917,1925,64,7.60,Aamir Khan,Abhay Deol,25088,3600.00,28.00
Family,E.T. the Extra-Terrestrial,1971,100,7.80,Mel Stuart,Gene Wilder,178731,4000000.00,67.00
Fantasy,Das Cabinet des Dr. Caligari,1920,76,7.90,F.W. Murnau,Max Schreck,57428,337574718.00,NaN
Film-Noir,Shadow of a Doubt,1941,100,7.80,Alfred Hitchcock,Humphrey Bogart,59556,449191.00,94.00
Horror,Alien,1933,71,7.60,Alejandro Amenábar,Anthony Perkins,27007,89029.00,46.00
Mystery,Dark City,1938,96,7.60,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.00,52.00
Thriller,Wait Until Dark,1967,108,7.80,Terence Young,Audrey Hepburn,27733,17550741.00,81.00
Western,"Il buono, il brutto, il cattivo",1965,132,7.80,Clint Eastwood,Clint Eastwood,65659,5321508.00,69.00

In [7]:
genres.mean(numeric_only = True)

           Runtime  IMDB_Rating  No_of_Votes        Gross  Metascore
Genre
Action      129.05         7.95    420246.58 189722449.50      73.42
Adventure   134.11         7.94    313557.82 131901700.89      78.44
Animation    99.59         7.93    268032.07 178432598.15      81.09
Biography   136.02         7.94    272805.05  94049518.25      76.24
Comedy      112.13         7.90    178195.66 101057213.97      78.72
Crime       126.39         8.02    313398.27  78996559.89      77.08
Drama       124.74         7.96    212343.61 122525861.73      79.70
Family      107.50         7.80    275610.50 219555277.00      79.00
Fantasy      85.00         8.00     73111.00 391363348.00        NaN
Film-Noir   104.00         7.97    122405.00  41970181.00      95.67
Horror      102.09         7.91    340232.36  94059021.64      80.00
Mystery     119.08         7.98    350250.33 104701417.92      79.12
Thriller    108.00         7.80     27733.00  17550741.00      81.00
Western     148.25         8.35    322416.25  14555377.00      78.25

# Examples

In [8]:
# 1. Find top 3 genres by total earning
imdb.groupby('Genre').sum(numeric_only = True) ['Gross'].sort_values(ascending = False).head(3)

Genre
Drama    35409974041.00
Action   32632261314.00
Comedy   15663868165.00
Name: Gross, dtype: float64

In [9]:
# 2. Find top 3 Genres whose average rating is the highest.

imdb.groupby('Genre') ["IMDB_Rating"].mean().sort_values(ascending = False).head(3)

Genre
Western   8.35
Crime     8.02
Fantasy   8.00
Name: IMDB_Rating, dtype: float64

In [10]:
# 3. Find most popular director based on votes

imdb.groupby('Director')['No_of_Votes'].sum().sort_values(ascending = False).head(3)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
Name: No_of_Votes, dtype: int64

In [11]:
# 4. Find the highest rated movie of each genre

imdb.groupby("Genre") [["Series_Title", "IMDB_Rating"]].max().sort_values(by = "IMDB_Rating", ascending = False)

                                  Series_Title  IMDB_Rating
Genre
Drama                                Zwartboek         9.30
Crime                        À bout de souffle         9.20
Action                                 Yôjinbô         9.00
Biography                              Zerkalo         8.90
Western                 The Outlaw Josey Wales         8.80
Adventure                           Zombieland         8.60
Animation          Ôkami kodomo no Ame to Yuki         8.60
Comedy                Zindagi Na Milegi Dobara         8.60
Horror                               The Thing         8.50
Mystery                                Vertigo         8.40
Fantasy                              Nosferatu         8.10
Film-Noir                        The Third Man         8.10
Family     Willy Wonka & the Chocolate Factory         7.80
Thriller                       Wait Until Dark         7.80

In [12]:
imdb[imdb['Genre'] == 'Drama'] [['Series_Title', 'IMDB_Rating']].max()

Series_Title    Zwartboek
IMDB_Rating          9.30
dtype: object

In [13]:
# 5. Find total no_of_movies done by each actor

imdb.columns

Index(['Series_Title', 'Released_Year', 'Runtime', 'Genre', 'IMDB_Rating',
       'Director', 'Star1', 'No_of_Votes', 'Gross', 'Metascore'],
      dtype='object')

In [14]:
imdb.groupby('Star1') ['Series_Title'].count()

# Apply groupby on Star1.
# Select any column so that we can apply aggregate operation.
# count() will simply count the no_of_rows in each group
# imdb['Star1'].value_counts()

Star1
Aamir Khan              7
Aaron Taylor-Johnson    1
Abhay Deol              1
Abraham Attah           1
Adam Driver             1
                       ..
Zbigniew Zamachowski    1
Zooey Deschanel         1
Çetin Tekindor          1
Éric Toledano           1
Ömer Faruk Sorak        1
Name: Series_Title, Length: 660, dtype: int64

# Always follow below 3 steps
`90% Problems will get solved with below 3 steps.`
1. apply groupby()
2. Get your desired column
3. Perform Aggregate operations


# `groupby` attributes and methods.

* find total number of groups -> len()
* find items in each group -> size
* first()/last() -> nth item
* get_group() -> vs filtering
* groups
* describe()
* sample()
* nunique()

In [15]:
# Find total no of groups formed: len()

len(imdb.groupby("Genre"))
# imdb['Genre'].nunique()

14

In [16]:
# Find items in each group: size

# imdb.groupby('Genre') ['Series_Title'].count().sort_values(ascending=False)
# imdb['Genre'].value_counts()
# imdb.groupby('Genre').size()

In [17]:
genre = imdb.groupby("Genre")

In [18]:
# first()/last(): Retruns the first and last movie of each Genre, respectively
# first(): Enters into the each group and returns the first movie
# last():  Enters into the each group and returns the last movie
# nth():  Enters into the each group and returns the nth movie

# genre.first()
# genre.last()
# genre.nth(9)    # Will return the 10th movie of each group
genre.nth(9).set_index("Genre")    # Will return the 10th movie of each group

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Shichinin no samurai,1954,207,8.60,Akira Kurosawa,Toshirô Mifune,315744,269061.00,98.00
Crime,The Departed,2006,151,8.50,Martin Scorsese,Leonardo DiCaprio,1189773,132384315.00,85.00
Drama,American History X,1998,119,8.50,Tony Kaye,Edward Norton,1034705,6719864.00,62.00
Comedy,The Sting,1973,129,8.30,George Roy Hill,Paul Newman,241513,159600000.00,83.00
Animation,Klaus,2019,96,8.20,Sergio Pablos,Carlos Martínez López,104761,148596026.00,65.00
Biography,Bhaag Milkha Bhaag,2013,186,8.20,Rakeysh Omprakash Mehra,Farhan Akhtar,61137,1626289.00,NaN
Adventure,The Great Escape,1963,172,8.20,John Sturges,Steve McQueen,224730,12100000.00,86.00
Mystery,El cuerpo,2012,112,7.60,Oriol Paulo,Jose Coronado,57549,140340673.00,NaN
Horror,Saw,2004,103,7.60,James Wan,Cary Elwes,379020,56000369.00,46.00

In [19]:
# get_group(): We can get all the rows of a particular group

genre.get_group("Action")

# We can also do this by filtering
# imdb[imdb['Genre'] == 'Action']

# get_group is falst bcz it has already created gropus and the filtering will perform filter every time.

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.00,Christopher Nolan,Christian Bale,2303232,534858444.00,84.00
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.90,Peter Jackson,Elijah Wood,1642758,377845905.00,94.00
8,Inception,2010,148,Action,8.80,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.00,74.00
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.80,Peter Jackson,Elijah Wood,1661481,315544750.00,92.00
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.70,Peter Jackson,Elijah Wood,1485555,342551365.00,87.00
...,...,...,...,...,...,...,...,...,...,...
968,Falling Down,1993,113,Action,7.60,Joel Schumacher,Michael Douglas,171640,40903593.00,56.00
979,Lethal Weapon,1987,109,Action,7.60,Richard Donner,Mel Gibson,236894,65207127.00,68.00
982,Mad Max 2,1981,96,Action,7.60,George Miller,Mel Gibson,166588,12465371.00,77.00
983,The Warriors,1979,92,Action,7.60,Walter Hill,Michael Beck,93878,22490039.00,65.00
985,Escape from Alcatraz,1979,112,Action,7.60,Don Siegel,Clint Eastwood,121731,43000000.00,76.00

In [20]:
# groups(): This returns a dictionary where keys are the names of the groups created,
# and values are list of indices or each group
# Rarely used.

genres.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [21]:
# describe: Returns statistics of each group

genre.describe()

          Runtime                                                 IMDB_Rating  \
            count   mean   std    min    25%    50%    75%    max       count
Genre
Action     172.00 129.05 28.50  45.00 110.75 127.50 143.25 321.00      172.00
Adventure   72.00 134.11 33.32  88.00 109.00 127.00 149.00 228.00       72.00
Animation   82.00  99.59 14.53  71.00  90.00  99.50 106.75 137.00       82.00
Biography   88.00 136.02 25.51  93.00 120.00 129.00 146.25 209.00       88.00
Comedy     155.00 112.13 22.95  68.00  96.00 106.00 124.50 188.00      155.00
Crime      107.00 126.39 27.69  80.00 106.50 122.00 141.50 229.00      107.00
Drama      289.00 124.74 27.74  64.00 105.00 121.00 137.00 242.00      289.00
Family       2.00 107.50 10.61 100.00 103.75 107.50 111.25 115.00        2.00
Fantasy      2.00  85.00 12.73  76.00  80.50  85.00  89.50  94.00        2.00
Film-Noir    3.00 104.00  4.00 100.00 102.00 104.00 106.00 108.00        3.00
Horror      11.00 102.09 13.60  71.00  98.00 103.00 109.00 122.00       11.00
Mystery     12.00 119.08 14.48  96.00 110.75 117.50 130.25 138.00       12.00
Thriller     1.00 108.00   NaN 108.00 108.00 108.00 108.00 108.00        1.00
Western      4.00 148.25 17.15 132.00 134.25 148.00 162.00 165.00        4.00

                ...        Gross              Metascore                    \
          mean  ...          75%          max     count  mean   std   min
Genre           ...
Action    7.95  ... 267443695.75 936662225.00    143.00 73.42 12.42 33.00
Adventure 7.94  ... 199806998.25 874211619.00     64.00 78.44 12.35 41.00
Animation 7.93  ... 252061158.75 873839108.00     75.00 81.09  8.81 61.00
Biography 7.94  ...  98299242.75 753585104.00     79.00 76.24 11.03 48.00
Comedy    7.90  ...  81078088.50 886752933.00    125.00 78.72 11.83 45.00
Crime     8.02  ...  71021626.00 790482117.00     87.00 77.08 13.10 47.00
Drama     7.96  ... 116446147.00 924558264.00    241.00 79.70 12.74 28.00
Family    7.80  ... 327332915.50 435110554.00      2.00 79.00 16.97 67.00
Fantasy   8.00  ... 418257663.00 445151978.00      0.00   NaN   NaN   NaN
Film-Noir 7.97  ...  62730676.00 123353292.00      3.00 95.67  1.53 94.00
Horror    7.91  ... 136281676.00 298791505.00     11.00 80.00 15.36 46.00
Mystery   7.97  ... 131094868.75 474203697.00      8.00 79.12 18.60 52.00
Thriller  7.80  ...  17550741.00  17550741.00      1.00 81.00   NaN 81.00
Western   8.35  ...  19200000.00  31800000.00      4.00 78.25  9.03 69.00


            25%   50%   75%    max
Genre
Action    65.00 74.00 82.00  98.00
Adventure 69.75 80.50 87.25 100.00
Animation 75.00 82.00 87.50  96.00
Biography 70.50 76.00 84.50  97.00
Comedy    72.00 79.00 88.00  99.00
Crime     69.50 77.00 87.00 100.00
Drama     72.00 82.00 89.00 100.00
Family    73.00 79.00 85.00  91.00
Fantasy     NaN   NaN   NaN    NaN
Film-Noir 95.00 96.00 96.50  97.00
Horror    77.50 87.00 88.50  97.00
Mystery   65.25 77.00 98.50 100.00
Thriller  81.00 81.00 81.00  81.00
Western   72.75 77.00 82.50  90.00

[14 rows x 40 columns]

In [22]:
# sample(): Returns one movie from each group

# len(genre)
# genre.sample()
# genre.sample(5)
genre.sample(2, replace = True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
216,Rush,2013,123,Action,8.10,Ron Howard,Daniel Brühl,432811,26947624.00,74.00
852,The French Connection,1971,104,Action,7.70,William Friedkin,Gene Hackman,110075,15630710.00,94.00
912,Zombieland,2009,88,Adventure,7.60,Ruben Fleischer,Jesse Eisenberg,520041,75590286.00,73.00
797,"O Brother, Where Art Thou?",2000,107,Adventure,7.70,Joel Coen,Ethan Coen,286742,45512588.00,69.00
242,Finding Nemo,2003,100,Animation,8.10,Andrew Stanton,Lee Unkrich,949565,380843261.00,90.00
246,Shin seiki Evangelion Gekijô-ban: Air/Magokoro...,1997,87,Animation,8.10,Hideaki Anno,Kazuya Tsurumaki,38847,364744762.00,NaN
753,Argo,2012,120,Biography,7.70,Ben Affleck,Ben Affleck,572581,136025503.00,86.00
102,Braveheart,1995,178,Biography,8.30,Mel Gibson,Mel Gibson,959181,75600000.00,68.00
967,Trois couleurs: Blanc,1994,92,Comedy,7.60,Krzysztof Kieslowski,Zbigniew Zamachowski,64390,1464625.00,88.00
381,Vizontele,2001,110,Comedy,8.00,Yilmaz Erdogan,Ömer Faruk Sorak,33592,200178699.00,NaN
833,Der Name der Rose,1986,130,Crime,7.70,Jean-Jacques Annaud,Sean Connery,102031,7153487.00,54.00
103,Reservoir Dogs,1992,99,Crime,8.30,Quentin Tarantino,Harvey Keitel,918562,2832029.00,79.00
765,Efter brylluppet,2006,120,Drama,7.70,Susanne Bier,Mads Mikkelsen,32001,412544.00,78.00
196,Pink,2016,136,Drama,8.10,Aniruddha Roy Chowdhury,Taapsee Pannu,39216,1241223.00,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.80,Steven Spielberg,Henry Thomas,372490,435110554.00,91.00
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.80,Mel Stuart,Gene Wilder,178731,4000000.00,67.00
568,Nosferatu,1922,94,Fantasy,7.90,F.W. Murnau,Max Schreck,88794,445151978.00,NaN
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.10,Robert Wiene,Werner Krauss,57428,337574718.00,NaN
712,Shadow of a Doubt,1943,108,Film-Noir,7.80,Alfred Hitchcock,Teresa Wright,59556,123353292.00,94.00
309,The Third Man,1949,104,Film-Noir,8.10,Carol Reed,Orson Welles,158731,449191.00,97.00
49,Psycho,1960,109,Horror,8.50,Alfred Hitchcock,Anthony Perkins,604211,32000000.00,97.00
844,Halloween,1978,91,Horror,7.70,John Carpenter,Donald Pleasence,233106,47000000.00,87.00
959,Dark City,1998,100,Mystery,7.60,Alex Proyas,Rufus Sewell,187927,14378331.00,66.00
69,Memento,2000,113,Mystery,8.40,Christopher Nolan,Guy Pearce,1125712,25544867.00,80.00
700,Wait Until Dark,1967,108,Thriller,7.80,Terence Young,Audrey Hepburn,27733,17550741.00,81.00
700,Wait Until Dark,1967,108,Thriller,7.80,Terence Young,Audrey Hepburn,27733,17550741.00,81.00
48,Once Upon a Time in the West,1968,165,Western,8.50,Sergio Leone,Henry Fonda,302844,5321508.00,80.00
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.80,Sergio Leone,Clint Eastwood,688390,6100000.00,90.00

In [23]:
# nunique(): Returns total no of unique rows present in each group

genre.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

# Some other functions

In [24]:
# agg(), pasing dictionary: Till now, we were applying single aggregare function like min(), max(), sum() etc
# But if we want, we can also apply multiple aggregate functions using agg() method.

genre.agg(
    {
        'Runtime': 'mean',
        'IMDB_Rating': 'mean',
        'No_of_Votes': 'sum',
        'Gross': 'sum',
        'Metascore': 'min'
    }
)

# genre.get_group("Action")['Metascore'].min()

           Runtime  IMDB_Rating  No_of_Votes          Gross  Metascore
Genre
Action      129.05         7.95     72282412 32632261314.00      33.00
Adventure   134.11         7.94     22576163  9496922464.00      41.00
Animation    99.59         7.93     21978630 14631473048.00      61.00
Biography   136.02         7.94     24006844  8276357606.00      48.00
Comedy      112.13         7.90     27620327 15663868165.00      45.00
Crime       126.39         8.02     33533615  8452631908.00      47.00
Drama       124.74         7.96     61367304 35409974041.00      28.00
Family      107.50         7.80       551221   439110554.00      67.00
Fantasy      85.00         8.00       146222   782726696.00        NaN
Film-Noir   104.00         7.97       367215   125910543.00      94.00
Horror      102.09         7.91      3742556  1034649238.00      46.00
Mystery     119.08         7.98      4203004  1256417015.00      52.00
Thriller    108.00         7.80        27733    17550741.00      81.00
Western     148.25         8.35      1289665    58221508.00      69.00

In [25]:
# agg(): Find min, max and average of each column

genre.agg(
    {
        'Runtime': ['min', 'max', 'mean'],
        'Gross': ['min', 'max', 'mean'],
        'No_of_Votes': ['min',  'max', 'mean']
    }
)

          Runtime                    Gross                            \
              min  max   mean          min          max         mean
Genre
Action         45  321 129.05      3296.00 936662225.00 189722449.50
Adventure      88  228 134.11     61001.00 874211619.00 131901700.89
Animation      71  137  99.59    128985.00 873839108.00 178432598.15
Biography      93  209 136.02     21877.00 753585104.00  94049518.25
Comedy         68  188 112.13      1305.00 886752933.00 101057213.97
Crime          80  229 126.39      6013.00 790482117.00  78996559.89
Drama          64  242 124.74      3600.00 924558264.00 122525861.73
Family        100  115 107.50   4000000.00 435110554.00 219555277.00
Fantasy        76   94  85.00 337574718.00 445151978.00 391363348.00
Film-Noir     100  108 104.00    449191.00 123353292.00  41970181.00
Horror         71  122 102.09     89029.00 298791505.00  94059021.64
Mystery        96  138 119.08   1035953.00 474203697.00 104701417.92
Thriller      108  108 108.00  17550741.00  17550741.00  17550741.00
Western       132  165 148.25   5321508.00  31800000.00  14555377.00

          No_of_Votes
                  min      max      mean
Genre
Action          25312  2303232 420246.58
Adventure       29999  1512360 313557.82
Animation       25229   999790 268032.07
Biography       27254  1213505 272805.05
Comedy          26337   939631 178195.66
Crime           27712  1826188 313398.27
Drama           25088  2343110 212343.61
Family         178731   372490 275610.50
Fantasy         57428    88794  73111.00
Film-Noir       59556   158731 122405.00
Horror          27007   787806 340232.36
Mystery         33982  1129894 350250.33
Thriller        27733    27733  27733.00
Western         65659   688390 322416.25

In [26]:
# looping on the group 

for group_object, data in genre:
    print(data['IMDB_Rating'])

2     9.00
5     8.90
8     8.80
10    8.80
13    8.70
      ...
968   7.60
979   7.60
982   7.60
983   7.60
985   7.60
Name: IMDB_Rating, Length: 172, dtype: float64
21    8.60
47    8.50
93    8.30
110   8.30
114   8.30
      ...
957   7.60
964   7.60
966   7.60
984   7.60
991   7.60
Name: IMDB_Rating, Length: 72, dtype: float64
23    8.60
43    8.50
46    8.50
56    8.40
58    8.40
      ...
956   7.60
971   7.60
976   7.60
986   7.60
992   7.60
Name: IMDB_Rating, Length: 82, dtype: float64
7     8.90
15    8.70
18    8.60
35    8.50
38    8.50
      ...
923   7.60
940   7.60
949   7.60
952   7.60
987   7.60
Name: IMDB_Rating, Length: 88, dtype: float64
19    8.60
26    8.60
51    8.50
52    8.50
64    8.40
      ...
977   7.60
978   7.60
989   7.60
994   7.60
995   7.60
Name: IMDB_Rating, Length: 155, dtype: float64
1     9.20
3     9.00
4     9.00
6     8.90
22    8.60
      ...
958   7.60
960   7.60
974   7.60
980   7.60
999   7.60
Name: IMDB_Rating, Length: 107, dtype: float64
0     9.30
9     8.80
11    8.80
17    8.70
20    8.60
      ...
990   7.60
993   7.60
996   7.60
997   7.60
998   7.60
Name: IMDB_Rating, Length: 289, dtype: float64
688   7.80
698   7.80
Name: IMDB_Rating, dtype: float64
321   8.10
568   7.90
Name: IMDB_Rating, dtype: float64
309   8.10
456   8.00
712   7.80
Name: IMDB_Rating, dtype: float64
49    8.50
75    8.40
271   8.10
419   8.00
544   7.90
707   7.80
724   7.70
844   7.70
876   7.70
932   7.60
948   7.60
Name: IMDB_Rating, dtype: float64
69    8.40
81    8.40
119   8.30
145   8.20
220   8.10
393   8.00
420   8.00
714   7.80
829   7.70
899   7.60
959   7.60
961   7.60
Name: IMDB_Rating, dtype: float64
700   7.80
Name: IMDB_Rating, dtype: float64
12    8.80
48    8.50
115   8.30
691   7.80
Name: IMDB_Rating, dtype: float64

In [27]:
# apply: We can apply built-in functions but most importanr thing for apply function is, we can apply
# custom function as well.

# Find total no of movies starting with 'A' in each genre/ group
def count_a(group):
    print(group)
    return group

genre.apply(count_a)

                                          Series_Title Released_Year  Runtime  \
2                                      The Dark Knight          2008      152
5        The Lord of the Rings: The Return of the King          2003      201
8                                            Inception          2010      148
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
13               The Lord of the Rings: The Two Towers          2002      179
..                                                 ...           ...      ...
968                                       Falling Down          1993      113
979                                      Lethal Weapon          1987      109
982                                          Mad Max 2          1981       96
983                                       The Warriors          1979       92
985                               Escape from Alcatraz          1979      112

      Genre  IMDB_Rating           Director              Star1  No_of_Votes  \
2    Action         9.00  Christopher Nolan     Christian Bale      2303232
5    Action         8.90      Peter Jackson        Elijah Wood      1642758
8    Action         8.80  Christopher Nolan  Leonardo DiCaprio      2067042
10   Action         8.80      Peter Jackson        Elijah Wood      1661481
13   Action         8.70      Peter Jackson        Elijah Wood      1485555
..      ...          ...                ...                ...          ...
968  Action         7.60    Joel Schumacher    Michael Douglas       171640
979  Action         7.60     Richard Donner         Mel Gibson       236894
982  Action         7.60      George Miller         Mel Gibson       166588
983  Action         7.60        Walter Hill       Michael Beck        93878
985  Action         7.60         Don Siegel     Clint Eastwood       121731

           Gross  Metascore
2   534858444.00      84.00
5   377845905.00      94.00
8   292576195.00      74.00
10  315544750.00      92.00
13  342551365.00      87.00
..           ...        ...
968  40903593.00      56.00
979  65207127.00      68.00
982  12465371.00      77.00
983  22490039.00      65.00
985  43000000.00      76.00

[172 rows x 10 columns]
                       Series_Title Released_Year  Runtime      Genre  \
21                     Interstellar          2014      169  Adventure
47               Back to the Future          1985      116  Adventure
93             Inglourious Basterds          2009      153  Adventure
110                        Das Boot          1981      149  Adventure
114           2001: A Space Odyssey          1968      149  Adventure
..                              ...           ...      ...        ...
957  Fear and Loathing in Las Vegas          1998      118  Adventure
964                        Dead Man          1995      121  Adventure
966                       Apollo 13            PG      140  Adventure
984                The Muppet Movie          1979       95  Adventure
991                  Kelly's Heroes          1970      144  Adventure

     IMDB_Rating           Director                Star1  No_of_Votes  \
21          8.60  Christopher Nolan  Matthew McConaughey      1512360
47          8.50    Robert Zemeckis       Michael J. Fox      1058081
93          8.30  Quentin Tarantino            Brad Pitt      1267869
110         8.30  Wolfgang Petersen      Jürgen Prochnow       231855
114         8.30    Stanley Kubrick          Keir Dullea       603517
..           ...                ...                  ...          ...
957         7.60      Terry Gilliam          Johnny Depp       259753
964         7.60       Jim Jarmusch          Johnny Depp        90442
966         7.60         Ron Howard            Tom Hanks       269197
984         7.60      James Frawley           Jim Henson        32802
991         7.60    Brian G. Hutton       Clint Eastwood        45338

           Gross  Metascore
21  188020017.00      74.00
47  210609762.00      87.00
93  120540719.00      69.00
110  11487676.00      86.00
114  56954992.00      84.00
..           ...        ...
957  10680275.00      41.00
964   1037847.00      62.00
966 173837933.00      77.00
984  76657000.00      74.00
991   1378435.00      50.00

[72 rows x 10 columns]
                          Series_Title Released_Year  Runtime      Genre  \
23       Sen to Chihiro no kamikakushi          2001      125  Animation
43                       The Lion King          1994       88  Animation
46                      Hotaru no haka          1988       89  Animation
56                      Kimi no na wa.          2016      106  Animation
58   Spider-Man: Into the Spider-Verse          2018      117  Animation
..                                 ...           ...      ...        ...
956                              Mulan          1998       88  Animation
971                  Omohide poro poro          1991      118  Animation
976                 The Little Mermaid          1989       83  Animation
986                     Watership Down          1978       91  Animation
992                    The Jungle Book          1967       78  Animation

     IMDB_Rating             Director             Star1  No_of_Votes  \
23          8.60       Hayao Miyazaki     Daveigh Chase       651376
43          8.50         Roger Allers       Rob Minkoff       942045
46          8.50        Isao Takahata   Tsutomu Tatsumi       235231
56          8.40       Makoto Shinkai  Ryûnosuke Kamiki       194838
58          8.40      Bob Persichetti      Peter Ramsey       375110
..           ...                  ...               ...          ...
956         7.60        Tony Bancroft        Barry Cook       256906
971         7.60        Isao Takahata         Miki Imai        27071
976         7.60         Ron Clements       John Musker       237696
986         7.60         Martin Rosen       John Hubley        33656
992         7.60  Wolfgang Reitherman       Phil Harris       166409

           Gross  Metascore
23   10055859.00      96.00
43  422783777.00      88.00
46  150734678.00      94.00
56    5017246.00      79.00
58  190241310.00      87.00
..           ...        ...
956 120620254.00      71.00
971    453243.00      90.00
976 111543479.00      88.00
986 232841485.00      64.00
992 141843612.00      65.00

[82 rows x 10 columns]
          Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
7     Schindler's List          1993      195  Biography         8.90
15          Goodfellas          1990      146  Biography         8.70
18            Hamilton          2020      160  Biography         8.60
35    The Intouchables          2011      112  Biography         8.50
38         The Pianist          2002      150  Biography         8.50
..                 ...           ...      ...        ...          ...
923     La Vie En Rose          2007      140  Biography         7.60
940  Finding Neverland          2004      106  Biography         7.60
949               Blow          2001      124  Biography         7.60
952      The Hurricane          1999      146  Biography         7.60
987   Midnight Express          1978      121  Biography         7.60

             Director               Star1  No_of_Votes        Gross  Metascore
7    Steven Spielberg         Liam Neeson      1213505  96898818.00      94.00
15    Martin Scorsese      Robert De Niro      1020727  46836394.00      90.00
18        Thomas Kail  Lin-Manuel Miranda        55291 440984783.00      90.00
35    Olivier Nakache       Éric Toledano       760360  13182281.00      57.00
38     Roman Polanski        Adrien Brody       729603  32572577.00      85.00
..                ...                 ...          ...          ...        ...
923     Olivier Dahan    Marion Cotillard        82781  10301706.00      66.00
940      Marc Forster         Johnny Depp       198677  51680613.00      67.00
949         Ted Demme         Johnny Depp       240714  52990775.00      52.00
952    Norman Jewison   Denzel Washington        91557  50668906.00      74.00
987       Alan Parker          Brad Davis        73662  35000000.00      59.00

[88 rows x 10 columns]
                                       Series_Title Released_Year  Runtime  \
19                                     Gisaengchung          2019      132
26                                  La vita è bella          1997      116
51                                     Modern Times          1936       87
52                                      City Lights          1931       87
64                                         3 Idiots          2009      170
..                                              ...           ...      ...
977  The Naked Gun: From the Files of Police Squad!          1988       85
978                    Planes, Trains & Automobiles          1987       93
989                                The Long Goodbye          1973      112
994                              A Hard Day's Night          1964       87
995                          Breakfast at Tiffany's          1961      115

      Genre  IMDB_Rating         Director            Star1  No_of_Votes  \
19   Comedy         8.60     Bong Joon Ho     Kang-ho Song       552778
26   Comedy         8.60  Roberto Benigni  Roberto Benigni       623629
51   Comedy         8.50  Charles Chaplin  Charles Chaplin       217881
52   Comedy         8.50  Charles Chaplin  Charles Chaplin       167839
64   Comedy         8.40  Rajkumar Hirani       Aamir Khan       344445
..      ...          ...              ...              ...          ...
977  Comedy         7.60     David Zucker   Leslie Nielsen       152871
978  Comedy         7.60      John Hughes     Steve Martin       124773
989  Comedy         7.60    Robert Altman    Elliott Gould        26337
994  Comedy         7.60   Richard Lester      John Lennon        40351
995  Comedy         7.60    Blake Edwards   Audrey Hepburn       166544

           Gross  Metascore
19   53367844.00      96.00
26   57598247.00      59.00
51     163245.00      96.00
52      19181.00      99.00
64    6532908.00      67.00
..           ...        ...
977  78756177.00      76.00
978  49530280.00      72.00
989    959000.00      87.00
994  13780024.00      96.00
995 679874270.00      76.00

[155 rows x 10 columns]
                Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
1              The Godfather          1972      175  Crime         9.20
3     The Godfather: Part II          1974      202  Crime         9.00
4               12 Angry Men          1957       96  Crime         9.00
6               Pulp Fiction          1994      154  Crime         8.90
22            Cidade de Deus          2002      130  Crime         8.60
..                       ...           ...      ...    ...          ...
958              Funny Games          1997      108  Crime         7.60
960                 Sleepers          1996      147  Crime         7.60
974  The Godfather: Part III          1990      162  Crime         7.60
980             Blood Simple          1984       99  Crime         7.60
999             The 39 Steps          1935       86  Crime         7.60

                 Director           Star1  No_of_Votes        Gross  Metascore
1    Francis Ford Coppola   Marlon Brando      1620367 134966411.00     100.00
3    Francis Ford Coppola       Al Pacino      1129952  57300000.00      90.00
4            Sidney Lumet     Henry Fonda       689845   4360000.00      96.00
6       Quentin Tarantino   John Travolta      1826188 107928762.00      94.00
22     Fernando Meirelles      Kátia Lund       699256   7563397.00      79.00
..                    ...             ...          ...          ...        ...
958        Michael Haneke  Susanne Lothar        65058 217345863.00      69.00
960        Barry Levinson  Robert De Niro       186734  49100000.00      49.00
974  Francis Ford Coppola       Al Pacino       359809  66666062.00      60.00
980             Joel Coen      Ethan Coen        87745   2150000.00      82.00
999      Alfred Hitchcock    Robert Donat        51853 302787539.00      93.00

[107 rows x 10 columns]
                        Series_Title Released_Year  Runtime  Genre  \
0           The Shawshank Redemption          1994      142  Drama
9                         Fight Club          1999      139  Drama
11                      Forrest Gump          1994      142  Drama
17   One Flew Over the Cuckoo's Nest          1975      133  Drama
20                   Soorarai Pottru          2020      153  Drama
..                               ...           ...      ...    ...
990                     Giù la testa          1971      157  Drama
993                           Blowup          1966      111  Drama
996                            Giant          1956      201  Drama
997            From Here to Eternity          1953      118  Drama
998                         Lifeboat          1944       97  Drama

     IMDB_Rating                Director              Star1  No_of_Votes  \
0           9.30          Frank Darabont        Tim Robbins      2343110
9           8.80           David Fincher          Brad Pitt      1854740
11          8.80         Robert Zemeckis          Tom Hanks      1809221
17          8.70            Milos Forman     Jack Nicholson       918088
20          8.60           Sudha Kongara             Suriya        54995
..           ...                     ...                ...          ...
990         7.60            Sergio Leone        Rod Steiger        30144
993         7.60  Michelangelo Antonioni     David Hemmings        56513
996         7.60          George Stevens   Elizabeth Taylor        34075
997         7.60          Fred Zinnemann     Burt Lancaster        43374
998         7.60        Alfred Hitchcock  Tallulah Bankhead        26471

           Gross  Metascore
0    28341469.00      80.00
9    37030102.00      66.00
11  330252182.00      82.00
17  112000000.00      83.00
20  556832648.00        NaN
..           ...        ...
990    696690.00      77.00
993 632532802.00      82.00
996 195217415.00      84.00
997  30500000.00      85.00
998 852142728.00      78.00

[289 rows x 10 columns]
                            Series_Title Released_Year  Runtime   Genre  \
688           E.T. the Extra-Terrestrial          1982      115  Family
698  Willy Wonka & the Chocolate Factory          1971      100  Family

     IMDB_Rating          Director         Star1  No_of_Votes        Gross  \
688         7.80  Steven Spielberg  Henry Thomas       372490 435110554.00
698         7.80        Mel Stuart   Gene Wilder       178731   4000000.00

     Metascore
688      91.00
698      67.00
                     Series_Title Released_Year  Runtime    Genre  \
321  Das Cabinet des Dr. Caligari          1920       76  Fantasy
568                     Nosferatu          1922       94  Fantasy

     IMDB_Rating      Director          Star1  No_of_Votes        Gross  \
321         8.10  Robert Wiene  Werner Krauss        57428 337574718.00
568         7.90   F.W. Murnau    Max Schreck        88794 445151978.00

     Metascore
321        NaN
568        NaN
           Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
309       The Third Man          1949      104  Film-Noir         8.10
456  The Maltese Falcon          1941      100  Film-Noir         8.00
712   Shadow of a Doubt          1943      108  Film-Noir         7.80

             Director            Star1  No_of_Votes        Gross  Metascore
309        Carol Reed     Orson Welles       158731    449191.00      97.00
456       John Huston  Humphrey Bogart       148928   2108060.00      96.00
712  Alfred Hitchcock    Teresa Wright        59556 123353292.00      94.00
                 Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
49                     Psycho          1960      109  Horror         8.50
75                      Alien          1979      117  Horror         8.40
271                 The Thing          1982      109  Horror         8.10
419              The Exorcist          1973      122  Horror         8.00
544  Night of the Living Dead          1968       96  Horror         7.90
707             The Innocents          1961      100  Horror         7.80
724                   Get Out          2017      104  Horror         7.70
844                 Halloween          1978       91  Horror         7.70
876         The Invisible Man          1933       71  Horror         7.70
932                       Saw          2004      103  Horror         7.60
948                The Others          2001      101  Horror         7.60

               Director             Star1  No_of_Votes        Gross  Metascore
49     Alfred Hitchcock   Anthony Perkins       604211  32000000.00      97.00
75         Ridley Scott  Sigourney Weaver       787806  78900000.00      89.00
271      John Carpenter      Kurt Russell       371271  13782838.00      57.00
419    William Friedkin     Ellen Burstyn       362393 232906145.00      81.00
544    George A. Romero       Duane Jones       116557     89029.00      89.00
707        Jack Clayton      Deborah Kerr        27007   2616000.00      88.00
724        Jordan Peele    Daniel Kaluuya       492851 176040665.00      85.00
844      John Carpenter  Donald Pleasence       233106  47000000.00      87.00
876         James Whale      Claude Rains        30683 298791505.00      87.00
932           James Wan        Cary Elwes       379020  56000369.00      46.00
948  Alejandro Amenábar     Nicole Kidman       337651  96522687.00      74.00
          Series_Title Released_Year  Runtime    Genre  IMDB_Rating  \
69             Memento          2000      113  Mystery         8.40
81         Rear Window          1954      112  Mystery         8.40
119            Vertigo          1958      128  Mystery         8.30
145     Shutter Island          2010      138  Mystery         8.20
220            Kahaani          2012      122  Mystery         8.10
393     Twelve Monkeys          1995      129  Mystery         8.00
420             Sleuth          1972      138  Mystery         8.00
714  The Lady Vanishes          1938       96  Mystery         7.80
829          Spoorloos          1988      107  Mystery         7.70
899          El cuerpo          2012      112  Mystery         7.60
959          Dark City          1998      100  Mystery         7.60
961       Lost Highway          1997      134  Mystery         7.60

                 Director                     Star1  No_of_Votes        Gross  \
69      Christopher Nolan                Guy Pearce      1125712  25544867.00
81       Alfred Hitchcock             James Stewart       444074  36764313.00
119      Alfred Hitchcock             James Stewart       364368   3200000.00
145       Martin Scorsese         Leonardo DiCaprio      1129894 128012934.00
220           Sujoy Ghosh               Vidya Balan        57806   1035953.00
393         Terry Gilliam              Bruce Willis       578443  57141459.00
420  Joseph L. Mankiewicz          Laurence Olivier        44748   4081254.00
714      Alfred Hitchcock         Margaret Lockwood        47400 474203697.00
829        George Sluizer  Bernard-Pierre Donnadieu        33982 367916835.00
899           Oriol Paulo             Jose Coronado        57549 140340673.00
959           Alex Proyas              Rufus Sewell       187927  14378331.00
961           David Lynch              Bill Pullman       131101   3796699.00

     Metascore
69       80.00
81      100.00
119     100.00
145      63.00
220        NaN
393      74.00
420        NaN
714      98.00
829        NaN
899        NaN
959      66.00
961      52.00
        Series_Title Released_Year  Runtime     Genre  IMDB_Rating  \
700  Wait Until Dark          1967      108  Thriller         7.80

          Director           Star1  No_of_Votes       Gross  Metascore
700  Terence Young  Audrey Hepburn        27733 17550741.00      81.00

C:\Users\jugal\AppData\Local\Temp\ipykernel_8968\3363802765.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(count_a)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action         9.00  Christopher Nolan
         5        201    Action         8.90      Peter Jackson
         8        148    Action         8.80  Christopher Nolan
         10       178    Action         8.80      Peter Jackson
         13       179    Action         8.70      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller         7.80      Terence Young
Western  12       161   Western         8.80       Sergio Leone
         48       165   Western         8.50       Sergio Leone
         115      132   Western         8.30       Sergio Leone
         691      135   Western         7.80     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore
Genre
Action   2       Christian Bale      2303232 534858444.00      84.00
         5          Elijah Wood      1642758 377845905.00      94.00
         8    Leonardo DiCaprio      2067042 292576195.00      74.00
         10         Elijah Wood      1661481 315544750.00      92.00
         13         Elijah Wood      1485555 342551365.00      87.00
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733  17550741.00      81.00
Western  12      Clint Eastwood       688390   6100000.00      90.00
         48         Henry Fonda       302844   5321508.00      80.00
         115     Clint Eastwood       232772  15000000.00      74.00
         691     Clint Eastwood        65659  31800000.00      69.00

[1000 rows x 10 columns]

In [28]:
# continue

def count_a(group):
    return group['Series_Title'].str.startswith('A').sum()

In [29]:
genre.apply(count_a)

C:\Users\jugal\AppData\Local\Temp\ipykernel_8968\2681596422.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(count_a)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [30]:
# Give rank to each movie in the group according to IMDB_Rating

def rank_movie(group):
    group["rank"] = group['IMDB_Rating'].rank(ascending = False)
    return group
    


genre.apply(rank_movie)

C:\Users\jugal\AppData\Local\Temp\ipykernel_8968\96844023.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(rank_movie)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action         9.00  Christopher Nolan
         5        201    Action         8.90      Peter Jackson
         8        148    Action         8.80  Christopher Nolan
         10       178    Action         8.80      Peter Jackson
         13       179    Action         8.70      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller         7.80      Terence Young
Western  12       161   Western         8.80       Sergio Leone
         48       165   Western         8.50       Sergio Leone
         115      132   Western         8.30       Sergio Leone
         691      135   Western         7.80     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  rank
Genre
Action   2       Christian Bale      2303232 534858444.00      84.00  1.00
         5          Elijah Wood      1642758 377845905.00      94.00  2.00
         8    Leonardo DiCaprio      2067042 292576195.00      74.00  3.50
         10         Elijah Wood      1661481 315544750.00      92.00  3.50
         13         Elijah Wood      1485555 342551365.00      87.00  6.00
...                         ...          ...          ...        ...   ...
Thriller 700     Audrey Hepburn        27733  17550741.00      81.00  1.00
Western  12      Clint Eastwood       688390   6100000.00      90.00  1.00
         48         Henry Fonda       302844   5321508.00      80.00  2.00
         115     Clint Eastwood       232772  15000000.00      74.00  3.00
         691     Clint Eastwood        65659  31800000.00      69.00  4.00

[1000 rows x 11 columns]

In [31]:
# Find normalized imdb rating groupwise

def normalize(group):
    group['Norm_Rating'] = (group['IMDB_Rating'] - group['IMDB_Rating'].min()) / (group['IMDB_Rating'].max() - group['IMDB_Rating'].min())

    return group


genre.apply(normalize)

C:\Users\jugal\AppData\Local\Temp\ipykernel_8968\656054225.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(normalize)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action         9.00  Christopher Nolan
         5        201    Action         8.90      Peter Jackson
         8        148    Action         8.80  Christopher Nolan
         10       178    Action         8.80      Peter Jackson
         13       179    Action         8.70      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller         7.80      Terence Young
Western  12       161   Western         8.80       Sergio Leone
         48       165   Western         8.50       Sergio Leone
         115      132   Western         8.30       Sergio Leone
         691      135   Western         7.80     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232 534858444.00      84.00
         5          Elijah Wood      1642758 377845905.00      94.00
         8    Leonardo DiCaprio      2067042 292576195.00      74.00
         10         Elijah Wood      1661481 315544750.00      92.00
         13         Elijah Wood      1485555 342551365.00      87.00
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733  17550741.00      81.00
Western  12      Clint Eastwood       688390   6100000.00      90.00
         48         Henry Fonda       302844   5321508.00      80.00
         115     Clint Eastwood       232772  15000000.00      74.00
         691     Clint Eastwood        65659  31800000.00      69.00

              Norm_Rating
Genre
Action   2           1.00
         5           0.93
         8           0.86
         10          0.86
         13          0.79
...                   ...
Thriller 700          NaN
Western  12          1.00
         48          0.70
         115         0.50
         691         0.00

[1000 rows x 11 columns]

# Grouping on multiple columns

In [32]:
duo = imdb.groupby(by= ['Director', 'Star1'])

#size()
duo.size()

# get_group()

duo.get_group(
    (
        "Aamir Khan", "Amole Gupte"
    )
)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.40,Aamir Khan,Amole Gupte,168895,1223869.00,NaN

In [36]:
# Find the most earning actor director combo

duo['Gross'].sum().sort_values(ascending= False).head()

Director           Star1
Akira Kurosawa     Toshirô Mifune   2999876948.00
Anthony Russo      Joe Russo        2205039403.00
Billy Wilder       William Holden   1286778560.00
Christopher Nolan  Christian Bale   1242939866.00
Werner Herzog      Klaus Kinski     1124604968.00
Name: Gross, dtype: float64

In [62]:
# Find the best actor-genre combo in terms of average meta score

actor_genre = imdb.groupby(by = ['Star1', 'Genre']) ['Metascore'].mean().sort_values(ascending = False)
# print(actor_genre)
# print("="* (50))

# print(actor_genre.index)    # See, this is a multi-index series

# Below code will return a Multi-index series and series doesn't have columns to choose for sort_values()
# Sp series's sort_values does not have 'by' parameter. IT sorts only on values

# reset_index() will convert series to DataFrame
# imdb.groupby(by = ['Star1', 'Genre']) ['Metascore'].mean().sort_values(ascending = False).reset_index()

imdb.groupby(by = ['Star1', 'Genre']) ['Metascore'].mean().reset_index().sort_values(by = "Metascore", ascending = False).head()

# reset_index() converts the multi-index series to the DataFrame

               Star1    Genre  Metascore
230   Ellar Coltrane    Drama     100.00
329  Humphrey Bogart    Drama     100.00
360    James Stewart  Mystery     100.00
77       Bertil Guve    Drama     100.00
590     Orson Welles    Drama     100.00

# Session 19 - Complete
# Next: Task on seperate Dataset