# Day 14 - How to frame a Machine Learning problem.(Theory. Explained in book.)

There are mainly four ways to obtain the data. They're
1) CSV/TSV: Comma Seperated File and Tab Seperated File,
2) JSON/SQL,
3) Fetch through API and
4) Web Scrapping.

Here in this session, we'll learn with CSV files

# Opeaning a local csv file.

In [1]:
import pandas as pd

df = pd.read_csv(r'D:\Nikss\Self Pracitce\Machine Learning\15 Day-15\aug_train.csv')
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

# Opeaning a csv file from URL

# 1) sep parameter for TSV file

sep parameter means a 'seperator'. By default it is a comma(',').<br>
But to deal with TSV file, we'll hafta set it as a tab(' ').

In [2]:
df2 = pd.read_csv(r"D:\Nikss\Self Pracitce\Machine Learning\15 Day-15\movie_titles_metadata.tsv", sep = '\t')
df2

# Here, we can see that there are no columns. Instead our first row became header. So we'll have to cereate columns' names by our own.
# To do that, name parameter is used which takes a list object.

# Moreover. it is not so that here inDataFrame we are not getting headers, in original TSV file also there will be no headers.

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [3]:
l = ['Serial_no', "Movie_name", 'Release_year', 'Ratings', 'Votes', 'Genres']

df2 = pd.read_csv(r"D:\Nikss\Self Pracitce\Machine Learning\15 Day-15\movie_titles_metadata.tsv", sep = '\t', names = l)
df2

# We can see our headings are inserted and the first row which previously was set as header is again set to a row.

,Serial_no,Movie_name,Release_year,Ratings,Votes,Genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

# 2) index_col parameter.

This parameter is used to convert any column as an index.

In [4]:
df2 = pd.read_csv(r"movie_titles_metadata.tsv", sep = '\t', names = l, index_col = 'Serial_no')

In [5]:
df2

,Movie_name,Release_year,Ratings,Votes,Genres
Serial_no,,,,,
m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...
m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

# 3) header parameter. 

This is used to make any row as a header.

In [6]:
df3 = pd.read_csv(r"test.csv")

In [7]:
df3

# Here, we want our first row to be a header.

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
1,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [8]:
df3 = pd.read_csv(r"test.csv", header = 1)    # header = 1 means start the data from row at position 1. Row indexing sttarts from 0 
df3

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [9]:
df4 = pd.read_csv(r"test.csv", header = [1,2,3])    # header = 1 means start the data from row at position 1. Row indexing sttarts from 0 
df4

# This is useless. Just performed for trying. It makes 3 rows as headers.

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
0,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
1,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

# 4) usecols parameter.

* It takes list object and is used to select rows which we want to import from our original dataset.

In [10]:
df5  = pd.read_csv(r'aug_train.csv', usecols = ['gender', 'education_level'])
df5

      gender education_level
0       Male        Graduate
1       Male        Graduate
2        NaN        Graduate
3        NaN        Graduate
4       Male         Masters
...      ...             ...
19153   Male        Graduate
19154   Male        Graduate
19155   Male        Graduate
19156   Male     High School
19157    NaN  Primary School

[19158 rows x 2 columns]

In [11]:
df5[df5['gender'] == 'Male'].count()

gender             13221
education_level    12979
dtype: int64

In [12]:
df5[(
(df5['gender'] == 'Female') &
(df5['education_level'] == 'Graduate')
)].count()

gender             773
education_level    773
dtype: int64

In [13]:
df5.gender.value_counts()

Male      13221
Female     1238
Other       191
Name: gender, dtype: int64

# 5) squeeze parameter.

Though it may happen very rarely, but sometimes if we want only one column from the dataset, then in this case if 'sqeeze' parameter is set as True, then it doesn't become a pandas's dataframe instead becomes pandas's series.

In [14]:
df6  = pd.read_csv(r'aug_train.csv', usecols = ['gender'], squeeze = True)
print(df6.head(10))

0    Male
1    Male
2     NaN
3     NaN
4    Male
5     NaN
6    Male
7    Male
8    Male
9     NaN
Name: gender, dtype: object

C:\Users\jugal\AppData\Local\Temp\ipykernel_12236\945383457.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  df6  = pd.read_csv(r'aug_train.csv', usecols = ['gender'], squeeze = True)

In [15]:
print(type(df6))

<class 'pandas.core.series.Series'>

# 6) skiprows.

* It takes list object and inside list it takes rows' numbers which we don't want to input in our dataframe.
* We can also give function to it and it will remove rows according to that function

In [16]:
df7 = pd.read_csv(r'aug_train.csv')
df7.head()

# We want to ignore 8949 and 29725 so list = [0, 1]

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [17]:
df7 = pd.read_csv(r'aug_train.csv', skiprows = [1, 2])    # In 0 it considers column. So we started from 1
print(df7[['enrollee_id', 'gender']].head())

# See, removed first two rows

   enrollee_id gender
0        11561    NaN
1        33241    NaN
2          666   Male
3        21651    NaN
4        28806   Male

# 7) nrows.

This imports first 'n' no.of rows.

In [18]:
df7 = pd.read_csv(r'aug_train.csv', nrows = 100)
df7

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,12081,city_65,0.802,Male,Has relevent experience,Full time course,Graduate,STEM,9,50-99,Pvt Ltd,1,33,0.0
96,7364,city_160,0.920,NaN,No relevent experience,Full time course,High School,NaN,2,100-500,Pvt Ltd,1,142,0.0
97,11184,city_74,0.579,NaN,No relevent experience,Full time course,Graduate,STEM,2,100-500,Pvt Ltd,1,34,0.0
98,7016,city_65,0.802,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,50-99,Pvt Ltd,2,14,1.0
99,8695,city_11,0.550,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,10/49,Pvt Ltd,2,27,1.0

# 8) encoding parameter.

* Sometimes our file might not be a utf encoded. In such case if we will have to pass the encoder type of our file this parameter.
* If we don't know the encoded type, we will hafta change its encoding using some editors like **'Sublime text'**.

In [19]:
df8  = pd.read_csv("zomato.csv", encoding = 'latin-1')

In [20]:
df8

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

# 9) error_bad_lines parameter.

* It may happen sometimes that there are for e.g 10 columns in our dataset. But some 10-15 rows in between may have 11 columns. In this case, we will get an error message and we won't be able to load our data in pandas DataFrame.
* error_bad_lines parameter skips those rows and loads the other rows.  
* So to avoid that error message and to load our data, set **error_bad_lines** parameter as False.

# 10) dtypes paraeter.

* Python automatically set the data types of the columns based on the types of data inserted in it.
* But if we want to change that automatically set datatype, we can do it using **dtype** parameter.

* For e.g: Here in our dataset named "aug_train.csv" there's a column named 'target'. Its data type is float, but the values are 0 and 1. But as its data type is float, it simply takes more memory. So we can change its dtype to 'int' and save the memory.
* dtypes takes a dictionary as an input where columns' names are keys and desired data types are values.

In [21]:
df9 = pd.read_csv("aug_train.csv")
df9.info()

# See target columns's data tyoe is float. So let's change it to int.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

In [22]:
df9 = pd.read_csv("aug_train.csv", dtype = {'target': int})
df9.info()

# See, now target column's data type is integer.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  int32
dtypes: float64(1), int32(1), int64(2), object(10)
memory usage: 2.0+ MB

# 11) Handling dates. 

* Bydefault dates are stored as string datatype. So to keep it into date-time format, **parse_dates** parameter is used.
* It takes list object and inside list, takes name of the column we want to parse.
* Moreover if our dataset have 3 different columns for date, month and year; we can pass a dictionary where key is the 'new col_name' and the values are the index of the 3 columns in the form of list.

In [23]:
df10 = pd.read_csv("D:\\Nikss\\Self Pracitce\\Machine Learning\\15 Day-15\\IPL Matches 2008-2020.csv")
print(df10['date'].iloc[5:10])
print()
df10.info()

# We can see that dtype of date is 'object'. So now let's convert it to date dype.

5    21-04-2008
6    22-04-2008
7    23-04-2008
8    24-04-2008
9    25-04-2008
Name: date, dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 817 entries, 0 to 816
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               817 non-null    int64
 1   city             804 non-null    object
 2   date             817 non-null    object
 3   player_of_match  813 non-null    object
 4   venue            817 non-null    object
 5   neutral_venue    817 non-null    int64
 6   team1            817 non-null    object
 7   team2            817 non-null    object
 8   toss_winner      817 non-null    object
 9   toss_decision    817 non-null    object
 10  winner           813 non-null    object
 11  result           813 non-null    object
 12  result_margin    800 non-null    float64
 13  eliminator       813 non-null    object
 14  method           20 non-null     object
 15  umpire1          817 non-null    object
 16  umpire2          817 non-null    object
 17  Unnamed: 17      1 non-null      float64
 18  Unnamed: 18      1 non-null      float64
dtypes: float64(3), int64(2), object(14)
memory usage: 121.4+ KB

In [24]:
df10 = pd.read_csv("IPL Matches 2008-2020.csv", parse_dates = ['date'])
df10.head()
print()
print()

df10.info()

# Try with another data set. It's not working here

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 817 entries, 0 to 816
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               817 non-null    int64
 1   city             804 non-null    object
 2   date             817 non-null    object
 3   player_of_match  813 non-null    object
 4   venue            817 non-null    object
 5   neutral_venue    817 non-null    int64
 6   team1            817 non-null    object
 7   team2            817 non-null    object
 8   toss_winner      817 non-null    object
 9   toss_decision    817 non-null    object
 10  winner           813 non-null    object
 11  result           813 non-null    object
 12  result_margin    800 non-null    float64
 13  eliminator       813 non-null    object
 14  method           20 non-null     object
 15  umpire1          817 non-null    object
 16  umpire2          817 non-null    object
 17  Unnamed: 17      1 non-null      float64
 18  Unnamed: 18      1 non-null      float64
dtypes: float64(3), int64(2), object(14)
memory usage: 121.4+ KB

C:\Users\jugal\AppData\Local\Temp\ipykernel_12236\2332300974.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df10 = pd.read_csv("IPL Matches 2008-2020.csv", parse_dates = ['date'])

# 12) converters.

* converter parameter is used to transform the values of the columns. 
* for e.g: In the IPL dataset, if we want to change 'Royal Chalengers Banglore' to 'RCB', we can use this parameter.
* It takes a dictionary where **key** is a **column_name** and **value** is a *function**.

* So let's first create a function that renames the values of the column.
* Here, we will rename **Royal Challengers Banglore** to **RCB**

In [33]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    elif name == "Mumbai Indians":
        return "MI"
    else:
        return name

In [34]:
rename ("Royal Challengers Bangalore")

'RCB'

In [35]:
df11 = pd.read_csv("IPL Matches 2008-2020.csv", converters = {"team1": rename})
df11["team1"]

0                        RCB
1            Kings XI Punjab
2           Delhi Daredevils
3                         MI
4      Kolkata Knight Riders
               ...
812                       MI
813                      RCB
814           Delhi Capitals
815           Delhi Capitals
816                        0
Name: team1, Length: 817, dtype: object

# 13) na_values parameter:

There can be many missing values in the datasets. Now we know that dataset is created by any person. Every person represents the missing values in his own way. Some may be using '-', some may be using space, some 'N/A', some 'n/a'. So how can Python identify which are null values.

Here **na_values** parameter plays its role. It takes a list of potential characters which will be treated as missing values in the dataset.

In [37]:
missing_values = ['-', 'n/a', 'N/A', ' ', '*']
# Pass this missing_values variable to 'na_values' parameter while reading the file.

# chunksize parameter:
* Helps to Load a large dataset into chunks.
* It takes the no.of rows as value, that we want to load in one chunk.

In [42]:
df12 = pd.read_csv("aug_train.csv")
df12.shape

# We can see that here we've 19,158 rows. Let's load it into chunks of 5000 rows.

(19158, 14)

In [58]:
df12 = pd.read_csv("aug_train.csv", chunksize = 5000)
print(df12)
print()
for i in df12:
    print(i.shape)

    # How to print these chunks, how to deal with different chunks and perform different operations on it, all these we will learn in our 'Pandas' session
# of Python.

<pandas.io.parsers.readers.TextFileReader object at 0x0000024560484490>

(5000, 14)
(5000, 14)
(5000, 14)
(4158, 14)

# Day 16. Working with Json/SQL file.