In [1]:
import pandas as pd
import numpy as np

In [2]:
date = pd.read_csv("00 orders.csv")
time = pd.read_csv("01 messages.csv")

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
# Droping unwanted columns.
date.drop(columns = ['product_id', 'city_id', 'orders'], axis = 'columns', inplace = True)

Note: Whenever we import any dataset using pandas, datatype of its date's and time's columns is always object(String) bydefault.
So, our very first duty is to convert their datatype to datetime. See the datatypes below. We can clearly see dtype of 'date' column is an object.

Only after converting it to datetime, we'll be able to extract useful informations form it.

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [8]:
# Converting to date time.

date['date'] = pd.to_datetime(date['date'])
time['date'] = pd.to_datetime(time.date)

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

In [10]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

# 1) Extract year.

In [11]:
date['year'] = date['date'].dt.year

In [12]:
date.head()

        date  year
0 2019-12-10  2019
1 2018-08-15  2018
2 2018-10-23  2018
3 2019-08-17  2019
4 2019-01-06  2019

# 2) Extract month.

In [13]:
date['month'] = date['date'].dt.month

In [14]:
date.head()

        date  year  month
0 2019-12-10  2019     12
1 2018-08-15  2018      8
2 2018-10-23  2018     10
3 2019-08-17  2019      8
4 2019-01-06  2019      1

In [15]:
date['month_name'] = date['date'].dt.month_name()

In [16]:
date.head()

        date  year  month month_name
0 2019-12-10  2019     12   December
1 2018-08-15  2018      8     August
2 2018-10-23  2018     10    October
3 2019-08-17  2019      8     August
4 2019-01-06  2019      1    January

# 3) Extract days.

In [17]:
date['days'] = date['date'].dt.day

In [18]:
date.head()

        date  year  month month_name  days
0 2019-12-10  2019     12   December    10
1 2018-08-15  2018      8     August    15
2 2018-10-23  2018     10    October    23
3 2019-08-17  2019      8     August    17
4 2019-01-06  2019      1    January     6

# 4) Extract day of week.

In [19]:
date['day_of_week'] = date['date'].dt.dayofweek

In [20]:
date.head()

        date  year  month month_name  days  day_of_week
0 2019-12-10  2019     12   December    10            1
1 2018-08-15  2018      8     August    15            2
2 2018-10-23  2018     10    October    23            1
3 2019-08-17  2019      8     August    17            5
4 2019-01-06  2019      1    January     6            6

# 5) Extract day's name.

In [21]:
date['day_name'] = date['date'].dt.day_name()

In [22]:
date.head()

        date  year  month month_name  days  day_of_week   day_name
0 2019-12-10  2019     12   December    10            1    Tuesday
1 2018-08-15  2018      8     August    15            2  Wednesday
2 2018-10-23  2018     10    October    23            1    Tuesday
3 2019-08-17  2019      8     August    17            5   Saturday
4 2019-01-06  2019      1    January     6            6     Sunday

# 6) Extracting if the day is weekend or not.

In [23]:
date['is_weekend'] = np.where(date['day_name'].isin(['Saturday', 'Sunday']), 'Yes', 'No')

# Here, 'Yes' and 'No' is used for understanding. But in real life, always use 1 for 'Yes' and 0 for 'No'.

In [24]:
date.head()

        date  year  month month_name  days  day_of_week   day_name is_weekend
0 2019-12-10  2019     12   December    10            1    Tuesday         No
1 2018-08-15  2018      8     August    15            2  Wednesday         No
2 2018-10-23  2018     10    October    23            1    Tuesday         No
3 2019-08-17  2019      8     August    17            5   Saturday        Yes
4 2019-01-06  2019      1    January     6            6     Sunday        Yes

In [25]:
date[
(date['day_name'] == 'Saturday') |
(date['day_name'] == 'Sunday')
]

          date  year  month month_name  days  day_of_week  day_name is_weekend
3   2019-08-17  2019      8     August    17            5  Saturday        Yes
4   2019-01-06  2019      1    January     6            6    Sunday        Yes
8   2019-06-29  2019      6       June    29            5  Saturday        Yes
19  2019-04-13  2019      4      April    13            5  Saturday        Yes
20  2019-11-30  2019     11   November    30            5  Saturday        Yes
..         ...   ...    ...        ...   ...          ...       ...        ...
986 2019-08-18  2019      8     August    18            6    Sunday        Yes
988 2019-02-03  2019      2   February     3            6    Sunday        Yes
990 2018-10-28  2018     10    October    28            6    Sunday        Yes
991 2019-01-12  2019      1    January    12            5  Saturday        Yes
998 2019-03-03  2019      3      March     3            6    Sunday        Yes

[284 rows x 8 columns]

# 7) Extract week of the year.

In [26]:
date['week_of_year'] = date['date'].dt.week

C:\Users\jugal\AppData\Local\Temp\ipykernel_19764\1488491725.py:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  date['week_of_year'] = date['date'].dt.week

In [27]:
date.head()

,date,year,month,month_name,days,day_of_week,day_name,is_weekend,week_of_year
0,2019-12-10,2019,12,December,10,1,Tuesday,No,50
1,2018-08-15,2018,8,August,15,2,Wednesday,No,33
2,2018-10-23,2018,10,October,23,1,Tuesday,No,43
3,2019-08-17,2019,8,August,17,5,Saturday,Yes,33
4,2019-01-06,2019,1,January,6,6,Sunday,Yes,1

# 8) Extract quarter

In [28]:
date['quarter'] = date.date.dt.quarter

In [29]:
date.head()

,date,year,month,month_name,days,day_of_week,day_name,is_weekend,week_of_year,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,No,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,No,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,No,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,Yes,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,Yes,1,1

# 9) Extract semester.

In [30]:
date['semester'] = np.where(date['quarter'].isin([1, 2]), 1, 2)

In [31]:
date.head()

,date,year,month,month_name,days,day_of_week,day_name,is_weekend,week_of_year,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,No,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,No,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,No,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,Yes,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,Yes,1,1,1

In [32]:
date.dtypes

date            datetime64[ns]
year                     int64
month                    int64
month_name              object
days                     int64
day_of_week              int64
day_name                object
is_weekend              object
week_of_year             int64
quarter                  int64
semester                 int32
dtype: object

# Getting difference from today's date.

In [42]:
import datetime

In [54]:
today = datetime.datetime.today()
print(today)

2024-06-05 22:23:42.280087

In [55]:
# Extract days and time difference.

today - date['date']

0     1639 days 22:23:42.280087
1     2121 days 22:23:42.280087
2     2052 days 22:23:42.280087
3     1754 days 22:23:42.280087
4     1977 days 22:23:42.280087
                 ...
995   2067 days 22:23:42.280087
996   2008 days 22:23:42.280087
997   1856 days 22:23:42.280087
998   1921 days 22:23:42.280087
999   1695 days 22:23:42.280087
Name: date, Length: 1000, dtype: timedelta64[ns]

In [60]:
# Extract days from the difference.

(today - date['date']).dt.days

0      1639
1      2121
2      2052
3      1754
4      1977
       ...
995    2067
996    2008
997    1856
998    1921
999    1695
Name: date, Length: 1000, dtype: int64

In [73]:
# Extracting months' difference.

(today - date.date).dt.days / 30

0      54.633333
1      70.700000
2      68.400000
3      58.466667
4      65.900000
         ...
995    68.900000
996    66.933333
997    61.866667
998    64.033333
999    56.500000
Name: date, Length: 1000, dtype: float64

In [86]:
# Using 'timedelta()' function.

(today - date['date']) / np.timedelta64(1, 'M')

0      53.879813
1      69.715867
2      67.448880
3      57.658125
4      64.984764
         ...
995    67.941703
996    66.003265
997    61.009323
998    63.144890
999    55.719686
Name: date, Length: 1000, dtype: float64

In [87]:
np.round((today - date['date']) / np.timedelta64(1, 'M'),0)

0      54.0
1      70.0
2      67.0
3      58.0
4      65.0
       ...
995    68.0
996    66.0
997    61.0
998    63.0
999    56.0
Name: date, Length: 1000, dtype: float64

In [90]:
(today - date['date']) / np.timedelta64(1, 'Y')

0      4.489984
1      5.809656
2      5.620740
3      4.804844
4      5.415397
         ...
995    5.661809
996    5.500272
997    5.084110
998    5.262074
999    4.643307
Name: date, Length: 1000, dtype: float64

# 2) Working with time.

In [33]:
# Droping unwanted column 'msg'.
time.drop(columns = 'msg', axis = 'columns', inplace = True)

# Extracting hour, minute and second.

In [34]:
time['hour'] = time['date'].dt.hour

In [35]:
time.head()

                 date  hour
0 2013-12-15 00:50:00     0
1 2014-04-29 23:40:00    23
2 2012-12-30 00:21:00     0
3 2014-11-28 00:31:00     0
4 2013-10-26 23:11:00    23

In [36]:
time['minute'] = time['date'].dt.minute
time['second'] = time['date'].dt.second

In [37]:
time.head()

                 date  hour  minute  second
0 2013-12-15 00:50:00     0      50       0
1 2014-04-29 23:40:00    23      40       0
2 2012-12-30 00:21:00     0      21       0
3 2014-11-28 00:31:00     0      31       0
4 2013-10-26 23:11:00    23      11       0

# Extracting time part from date and time.

Here, date and time both are mentioned in the single cell. So let's seperate time from it

In [40]:
time['time'] = time['date'].dt.time

In [41]:
time.head()

                 date  hour  minute  second      time
0 2013-12-15 00:50:00     0      50       0  00:50:00
1 2014-04-29 23:40:00    23      40       0  23:40:00
2 2012-12-30 00:21:00     0      21       0  00:21:00
3 2014-11-28 00:31:00     0      31       0  00:31:00
4 2013-10-26 23:11:00    23      11       0  23:11:00

# Extracting time difference.

In [91]:
(today - time['date']) / np.timedelta64(1, 'm')    # 'm' stands for minute.

0      5.509294e+06
1      5.313524e+06
2      6.013323e+06
3      5.008193e+06
4      5.579953e+06
           ...
995    6.429454e+06
996    5.451790e+06
997    6.121367e+06
998    6.288410e+06
999    5.240099e+06
Name: date, Length: 1000, dtype: float64

In [101]:
(today - time.date) / np.timedelta64(1, 's')    # 's' stands for second

0      3.305576e+08
1      3.188114e+08
2      3.607994e+08
3      3.004916e+08
4      3.347972e+08
           ...
995    3.857672e+08
996    3.271074e+08
997    3.672820e+08
998    3.773046e+08
999    3.144059e+08
Name: date, Length: 1000, dtype: float64

In [104]:
(today - date['date']) / np.timedelta64(1, 'h')   # 'h' stands for hour

0      39358.395078
1      50926.395078
2      49270.395078
3      42118.395078
4      47470.395078
           ...
995    49630.395078
996    48214.395078
997    44566.395078
998    46126.395078
999    40702.395078
Name: date, Length: 1000, dtype: float64