# What are pipelines?

* Pipelines chains together multiple tasks so that the output of each task is used as an imput to the next task
* Pipelines makes it easy to apply same preprocessing to train and test.
* It's ok if not understand clearly, we will work with and without pipelines both and see the difference.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("29 titanic.csv")

In [3]:
df.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
210,211,0,3,"Ali, Mr. Ahmed",male,24.00,0,0,SOTON/O.Q. 3101311,7.0500,NaN,S
224,225,1,1,"Hoyt, Mr. Frederick Maxfield",male,38.00,1,0,19943,90.0000,C93,S
717,718,1,2,"Troutt, Miss. Edwina Celia ""Winnie""",female,27.00,0,0,34218,10.5000,E101,S
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.00,0,0,A/5. 2151,8.0500,NaN,S
303,304,1,2,"Keane, Miss. Nora A",female,NaN,0,0,226593,12.3500,E101,Q
848,849,0,2,"Harper, Rev. John",male,28.00,0,1,248727,33.0000,NaN,S
369,370,1,1,"Aubart, Mme. Leontine Pauline",female,24.00,0,0,PC 17477,69.3000,B35,C
870,871,0,3,"Balkic, Mr. Cerin",male,26.00,0,0,349248,7.8958,NaN,S
766,767,0,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C

In [4]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
# Our aim is not model building but to understand the concept. So we are droping some unnecessary columns

df.drop(columns = ['PassengerId', 'Name', 'Cabin', "Ticket"], axis = 'columns', inplace = True)

In [6]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [7]:
# Splitting into 'x' and 'y'

x = df.iloc[:, 1:8]
y = df.drop(x, axis = 'columns')

print(x.head())
print()
print()
print(y.head())

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S


   Survived
0         0
1         1
2         1
3         1
4         0

In [8]:
# Train test split.

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)


print(x_train.isnull().sum())

Pclass        0
Sex           0
Age         138
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [9]:
# Applying imputatiion

from sklearn.impute import SimpleImputer

In [10]:
si_age = SimpleImputer()    # Imputing with mean(By default)
si_embarked = SimpleImputer(strategy = 'most_frequent')    # Imputing most frequent repeting element.

In [11]:
x_train_age = si_age.fit_transform(x_train[['Age']])
x_train_embarked = si_embarked.fit_transform(x_train[['Embarked']])

In [12]:
x_test_age = si_age.transform(x_test[['Age']])
x_test_embarked = si_embarked.transform(x_test[['Embarked']])

In [13]:
print(x_train_age[0:4])
print()
print()
print()
print(x_train_embarked[0:4])

[[ 1.]
 [21.]
 [25.]
 [20.]]



[['C']
 ['S']
 ['S']
 ['S']]

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
ohe_sex = OneHotEncoder(sparse = False, handle_unknown = 'ignore')
ohe_embarked = OneHotEncoder(sparse = False, handle_unknown = 'ignore')

In [16]:
x_train_sex = ohe_sex.fit_transform(x_train[['Sex']])
x_train_embarked = ohe_embarked.fit_transform(x_train_embarked)

C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [17]:
x_test_sex = ohe_sex.fit_transform(x_test[['Sex']])
x_test_embarked = ohe_embarked.fit_transform(x_test_embarked)

C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [18]:
print(x_train_embarked[0:4])

print()
print()
print()

print(x_test_embarked[0:4])

print()
print()
print()

print(x_train_sex[0:4])

print()
print()
print()

print(x_test_sex[0:4])

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]



[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]



[[0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]



[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]

# Concetenation

In [19]:
# Extraxting extra columns

x_train_rem = x_train.drop(columns = ['Age', 'Sex', 'Embarked'])
x_test_rem = x_test.drop(columns = ['Age', "Sex", 'Embarked'])

In [20]:
x_train_rem

     Pclass  SibSp  Parch     Fare
827       2      0      2  37.0042
106       3      0      0   7.6500
666       2      0      0  13.0000
664       3      1      0   7.9250
244       3      0      0   7.2250
..      ...    ...    ...      ...
516       2      0      0  10.5000
79        3      0      0  12.4750
785       3      0      0   7.2500
70        2      0      0  10.5000
848       2      0      1  33.0000

[712 rows x 4 columns]

In [21]:
x_train_trans = np.concatenate((x_train_rem, x_train_age, x_train_sex, x_train_embarked), axis = 1)
x_test_trans = np.concatenate((x_test_rem, x_test_age, x_test_sex, x_test_embarked), axis = 1)

In [22]:
x_train_trans[1]

array([ 3.  ,  0.  ,  0.  ,  7.65, 21.  ,  1.  ,  0.  ,  0.  ,  0.  ,
        1.  ])

In [23]:
x_test_trans[1]

array([ 3.    ,  0.    ,  0.    ,  8.4333, 21.    ,  0.    ,  1.    ,
        0.    ,  0.    ,  1.    ])

In [24]:
y_train.head(2)

     Survived
827         1
106         1

In [25]:
y_test.head(6)

     Survived
831         1
652         0
495         0
731         0
799         0
399         1

# Model building

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
dt = DecisionTreeClassifier()

In [28]:
dt.fit(x_train_trans, y_train)

DecisionTreeClassifier()

In [29]:
x_test_trans.shape

(179, 10)

In [30]:
y_test.shape

(179, 1)

In [31]:
pred = dt.predict(x_test_trans)

In [32]:
from sklearn.metrics import accuracy_score

In [33]:
accuracy = accuracy_score(pred, y_test)
print(accuracy)

0.7653631284916201

In [34]:
import pickle
import os

# Create the 'models' directory if it doesn't exist
os.makedirs('models', exist_ok=True)

In [37]:
pickle.dump(ohe_sex, open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked, open('models/ohe_embarked.pkl','wb'))
pickle.dump(dt, open('models/dt.pkl','wb'))

# Next stage: 02 Predicting withour using Pipeline.